/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type IndexedAssetsListRequestStatusItem = "ready" | "pending" | "queued" | "indexing" | "validating" | "failed";
export const IndexedAssetsListRequestStatusItem = {
    Ready: "ready",
    Pending: "pending",
    Queued: "queued",
    Indexing: "indexing",
    Validating: "validating",
    Failed: "failed",
} as const;
