/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../../index";

/**
 * @example
 *     {
 *         name: "Product Demo Analysis"
 *     }
 */
export interface KnowledgeStoresCreateRequest {
    /** The name of the knowledge store. */
    name: string;
    ingestionConfig?: TwelvelabsApi.IngestionConfig;
    /** An optional description of the knowledge store. */
    description?: string;
    /** Custom metadata for the knowledge store. Both keys and values must be strings. */
    metadata?: Record<string, string>;
}
