/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../../index";

/**
 * @example
 *     {
 *         query: {
 *             text: "A person cooking pasta"
 *         },
 *         searchOptions: {
 *             video: {
 *                 modalities: ["visual", "audio"]
 *             }
 *         },
 *         groupBy: "none",
 *         pageSize: 10
 *     }
 *
 * @example
 *     {
 *         query: {
 *             text: "A person cooking pasta"
 *         },
 *         filter: {
 *             assetType: {
 *                 in: ["video"]
 *             }
 *         },
 *         searchOptions: {
 *             video: {
 *                 modalities: ["visual", "audio"]
 *             }
 *         },
 *         groupBy: "none",
 *         pageSize: 10
 *     }
 *
 * @example
 *     {
 *         query: {
 *             text: "A person cooking pasta"
 *         },
 *         groupBy: "none",
 *         pageSize: 10
 *     }
 *
 * @example
 *     {
 *         query: {
 *             text: "A person cooking pasta"
 *         },
 *         searchOptions: {
 *             video: {
 *                 modalities: ["visual", "audio"]
 *             }
 *         },
 *         groupBy: "none",
 *         pageSize: 10
 *     }
 *
 * @example
 *     {
 *         query: {
 *             text: "A person cooking pasta"
 *         },
 *         searchOptions: {
 *             video: {
 *                 modalities: ["visual", "audio"]
 *             }
 *         },
 *         groupBy: "none",
 *         pageSize: 10
 *     }
 */
export interface SearchKnowledgeStoreRequest {
    query: TwelvelabsApi.KnowledgeStoreSearchQuery;
    filter?: TwelvelabsApi.SearchKnowledgeStoreFilter;
    searchOptions?: TwelvelabsApi.SearchKnowledgeStoreOptions;
    /**
     * Controls how the platform groups matches in the response.
     *
     * - `none`: Returns individual matches ordered by relevance.
     * - `item`: Groups matches under their parent item.
     *
     * **Default**: `none`.
     */
    groupBy?: TwelvelabsApi.SearchKnowledgeStoreRequestGroupBy;
    /**
     * The maximum number of results per page. A result is one entry in the `data` array. With the `group_by` parameter set to its default of `none`, each result is an individual match: a video clip or an image. When set to `item`, each result is one item: a video with all its matching clips, or an image.
     *
     * **Default**: `10`. **Max**: `50`.
     */
    pageSize?: number;
    /**
     * Pagination token used to retrieve the next page of results. Omit it on the first request. To fetch the next page, set it to the `next_page_token` field returned in the previous response and send the request again.
     *
     * A malformed or unrecognized token returns a `400` error. A token that has expired returns a `410` error (make a new search request to obtain a fresh page token).
     */
    pageToken?: string;
    /** Set to `true` to include metadata in each result. Each result includes a `metadata` object with a `system` field (platform-derived file properties such as duration and resolution) and a `user` field (metadata you attached to the item). */
    includeMetadata?: boolean;
}
