/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as TwelvelabsApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { IngestionConfig } from "../../../../types/IngestionConfig";
import { KnowledgeStoreMetadataValue } from "../../../../types/KnowledgeStoreMetadataValue";

export const KnowledgeStoresCreateRequest: core.serialization.Schema<
    serializers.KnowledgeStoresCreateRequest.Raw,
    TwelvelabsApi.KnowledgeStoresCreateRequest
> = core.serialization.object({
    name: core.serialization.string(),
    ingestionConfig: core.serialization.property("ingestion_config", IngestionConfig.optional()),
    description: core.serialization.string().optional(),
    metadata: core.serialization.record(core.serialization.string(), KnowledgeStoreMetadataValue).optional(),
});

export declare namespace KnowledgeStoresCreateRequest {
    export interface Raw {
        name: string;
        ingestion_config?: IngestionConfig.Raw | null;
        description?: string | null;
        metadata?: Record<string, KnowledgeStoreMetadataValue.Raw> | null;
    }
}
