/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as TwelvelabsApi from "../../../index";
import * as serializers from "../../../../serialization/index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace KnowledgeStoreItemCollections {
    export interface Options {
        environment?: core.Supplier<environments.TwelvelabsApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class KnowledgeStoreItemCollections {
    constructor(protected readonly _options: KnowledgeStoreItemCollections.Options) {}

    /**
     * Returns a list of the item collections in the specified knowledge store.
     *
     * @param {string} knowledgeStoreId - The unique identifier of the knowledge store.
     * @param {TwelvelabsApi.KnowledgeStoreItemCollectionsListRequest} request
     * @param {KnowledgeStoreItemCollections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     *
     * @example
     *     await client.knowledgeStoreItemCollections.list("ks_069e9869-1ea3-7481-8000-dae72bf6be6e", {
     *         page: 1,
     *         pageLimit: 10,
     *         sortBy: "created_at",
     *         sortOption: "desc"
     *     })
     */
    public async list(
        knowledgeStoreId: string,
        request: TwelvelabsApi.KnowledgeStoreItemCollectionsListRequest = {},
        requestOptions?: KnowledgeStoreItemCollections.RequestOptions,
    ): Promise<core.Page<TwelvelabsApi.KnowledgeStoreItemCollection>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TwelvelabsApi.KnowledgeStoreItemCollectionsListRequest,
            ): Promise<core.WithRawResponse<TwelvelabsApi.KnowledgeStoreItemCollectionsListResponse>> => {
                const { page, pageLimit, sortBy, sortOption } = request;
                const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
                if (page != null) {
                    _queryParams["page"] = page.toString();
                }
                if (pageLimit != null) {
                    _queryParams["page_limit"] = pageLimit.toString();
                }
                if (sortBy != null) {
                    _queryParams["sort_by"] = serializers.KnowledgeStoreItemCollectionsListRequestSortBy.jsonOrThrow(
                        sortBy,
                        { unrecognizedObjectKeys: "strip" },
                    );
                }
                if (sortOption != null) {
                    _queryParams["sort_option"] = sortOption;
                }
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.TwelvelabsApiEnvironment.Default,
                        `knowledge-stores/${encodeURIComponent(knowledgeStoreId)}/item-collections`,
                    ),
                    method: "GET",
                    headers: {
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "twelvelabs-js",
                        "X-Fern-SDK-Version": "1.3.4",
                        "User-Agent": "twelvelabs-js/1.3.4",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...(await this._getCustomAuthorizationHeaders()),
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    queryParameters: _queryParams,
                    requestType: "json",
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 600000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        data: serializers.KnowledgeStoreItemCollectionsListResponse.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                        default:
                            throw new errors.TwelvelabsApiError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.TwelvelabsApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                            rawResponse: _response.rawResponse,
                        });
                    case "timeout":
                        throw new errors.TwelvelabsApiTimeoutError(
                            "Timeout exceeded when calling GET /knowledge-stores/{knowledge_store_id}/item-collections.",
                        );
                    case "unknown":
                        throw new errors.TwelvelabsApiError({
                            message: _response.error.errorMessage,
                            rawResponse: _response.rawResponse,
                        });
                }
            },
        );
        let _offset = request?.page != null ? request?.page : 1;
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Pageable<
            TwelvelabsApi.KnowledgeStoreItemCollectionsListResponse,
            TwelvelabsApi.KnowledgeStoreItemCollection
        >({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) => (response?.data ?? []).length > 0,
            getItems: (response) => response?.data ?? [],
            loadPage: (_response) => {
                _offset += 1;
                return list(core.setObjectProperty(request, "page", _offset));
            },
        });
    }

    /**
     * Creates an item collection in the specified knowledge store. An item collection is a named collection of items. Use item collections to organize and reference subsets of items together.
     *
     * @param {string} knowledgeStoreId - The unique identifier of the knowledge store.
     * @param {TwelvelabsApi.KnowledgeStoreItemCollectionsCreateRequest} request
     * @param {KnowledgeStoreItemCollections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     *
     * @example
     *     await client.knowledgeStoreItemCollections.create("ks_069e9869-1ea3-7481-8000-dae72bf6be6e", {
     *         name: "Q1 highlights"
     *     })
     */
    public create(
        knowledgeStoreId: string,
        request: TwelvelabsApi.KnowledgeStoreItemCollectionsCreateRequest,
        requestOptions?: KnowledgeStoreItemCollections.RequestOptions,
    ): core.HttpResponsePromise<TwelvelabsApi.KnowledgeStoreItemCollection> {
        return core.HttpResponsePromise.fromPromise(this.__create(knowledgeStoreId, request, requestOptions));
    }

    private async __create(
        knowledgeStoreId: string,
        request: TwelvelabsApi.KnowledgeStoreItemCollectionsCreateRequest,
        requestOptions?: KnowledgeStoreItemCollections.RequestOptions,
    ): Promise<core.WithRawResponse<TwelvelabsApi.KnowledgeStoreItemCollection>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                `knowledge-stores/${encodeURIComponent(knowledgeStoreId)}/item-collections`,
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.3.4",
                "User-Agent": "twelvelabs-js/1.3.4",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.KnowledgeStoreItemCollectionsCreateRequest.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 600000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.KnowledgeStoreItemCollection.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError(
                    "Timeout exceeded when calling POST /knowledge-stores/{knowledge_store_id}/item-collections.",
                );
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieves the details of a specific item collection.
     *
     * @param {string} knowledgeStoreId - The unique identifier of the knowledge store.
     * @param {string} collectionId - The unique identifier of the knowledge store item collection.
     * @param {KnowledgeStoreItemCollections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     *
     * @example
     *     await client.knowledgeStoreItemCollections.retrieve("ks_069e9869-1ea3-7481-8000-dae72bf6be6e", "ksic_069e9870-3c4d-7abc-9012-3456789abcde")
     */
    public retrieve(
        knowledgeStoreId: string,
        collectionId: string,
        requestOptions?: KnowledgeStoreItemCollections.RequestOptions,
    ): core.HttpResponsePromise<TwelvelabsApi.KnowledgeStoreItemCollection> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(knowledgeStoreId, collectionId, requestOptions));
    }

    private async __retrieve(
        knowledgeStoreId: string,
        collectionId: string,
        requestOptions?: KnowledgeStoreItemCollections.RequestOptions,
    ): Promise<core.WithRawResponse<TwelvelabsApi.KnowledgeStoreItemCollection>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                `knowledge-stores/${encodeURIComponent(knowledgeStoreId)}/item-collections/${encodeURIComponent(collectionId)}`,
            ),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.3.4",
                "User-Agent": "twelvelabs-js/1.3.4",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 600000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.KnowledgeStoreItemCollection.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError(
                    "Timeout exceeded when calling GET /knowledge-stores/{knowledge_store_id}/item-collections/{collection_id}.",
                );
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Deletes the specified item collection. The items themselves remain in the knowledge store.
     *
     * @param {string} knowledgeStoreId - The unique identifier of the knowledge store.
     * @param {string} collectionId - The unique identifier of the knowledge store item collection.
     * @param {KnowledgeStoreItemCollections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     *
     * @example
     *     await client.knowledgeStoreItemCollections.delete("ks_069e9869-1ea3-7481-8000-dae72bf6be6e", "ksic_069e9870-3c4d-7abc-9012-3456789abcde")
     */
    public delete(
        knowledgeStoreId: string,
        collectionId: string,
        requestOptions?: KnowledgeStoreItemCollections.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(knowledgeStoreId, collectionId, requestOptions));
    }

    private async __delete(
        knowledgeStoreId: string,
        collectionId: string,
        requestOptions?: KnowledgeStoreItemCollections.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                `knowledge-stores/${encodeURIComponent(knowledgeStoreId)}/item-collections/${encodeURIComponent(collectionId)}`,
            ),
            method: "DELETE",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.3.4",
                "User-Agent": "twelvelabs-js/1.3.4",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 600000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError(
                    "Timeout exceeded when calling DELETE /knowledge-stores/{knowledge_store_id}/item-collections/{collection_id}.",
                );
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Updates the `name`, `description`, and `metadata` fields of the specified item collection.
     *
     * @param {string} knowledgeStoreId - The unique identifier of the knowledge store.
     * @param {string} collectionId - The unique identifier of the knowledge store item collection.
     * @param {TwelvelabsApi.KnowledgeStoreItemCollectionsUpdateRequest} request
     * @param {KnowledgeStoreItemCollections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     *
     * @example
     *     await client.knowledgeStoreItemCollections.update("ks_069e9869-1ea3-7481-8000-dae72bf6be6e", "ksic_069e9870-3c4d-7abc-9012-3456789abcde")
     */
    public update(
        knowledgeStoreId: string,
        collectionId: string,
        request: TwelvelabsApi.KnowledgeStoreItemCollectionsUpdateRequest = {},
        requestOptions?: KnowledgeStoreItemCollections.RequestOptions,
    ): core.HttpResponsePromise<TwelvelabsApi.KnowledgeStoreItemCollection> {
        return core.HttpResponsePromise.fromPromise(
            this.__update(knowledgeStoreId, collectionId, request, requestOptions),
        );
    }

    private async __update(
        knowledgeStoreId: string,
        collectionId: string,
        request: TwelvelabsApi.KnowledgeStoreItemCollectionsUpdateRequest = {},
        requestOptions?: KnowledgeStoreItemCollections.RequestOptions,
    ): Promise<core.WithRawResponse<TwelvelabsApi.KnowledgeStoreItemCollection>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                `knowledge-stores/${encodeURIComponent(knowledgeStoreId)}/item-collections/${encodeURIComponent(collectionId)}`,
            ),
            method: "PATCH",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.3.4",
                "User-Agent": "twelvelabs-js/1.3.4",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.KnowledgeStoreItemCollectionsUpdateRequest.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 600000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.KnowledgeStoreItemCollection.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError(
                    "Timeout exceeded when calling PATCH /knowledge-stores/{knowledge_store_id}/item-collections/{collection_id}.",
                );
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns a list of the items in the specified item collection.
     *
     * @param {string} knowledgeStoreId - The unique identifier of the knowledge store.
     * @param {string} collectionId - The unique identifier of the knowledge store item collection.
     * @param {TwelvelabsApi.KnowledgeStoreItemCollectionsListItemsRequest} request
     * @param {KnowledgeStoreItemCollections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     *
     * @example
     *     await client.knowledgeStoreItemCollections.listItems("ks_069e9869-1ea3-7481-8000-dae72bf6be6e", "ksic_069e9870-3c4d-7abc-9012-3456789abcde", {
     *         page: 1,
     *         pageLimit: 10
     *     })
     */
    public async listItems(
        knowledgeStoreId: string,
        collectionId: string,
        request: TwelvelabsApi.KnowledgeStoreItemCollectionsListItemsRequest = {},
        requestOptions?: KnowledgeStoreItemCollections.RequestOptions,
    ): Promise<core.Page<TwelvelabsApi.KnowledgeStoreItem>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TwelvelabsApi.KnowledgeStoreItemCollectionsListItemsRequest,
            ): Promise<core.WithRawResponse<TwelvelabsApi.KnowledgeStoreItemCollectionsListItemsResponse>> => {
                const { page, pageLimit } = request;
                const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
                if (page != null) {
                    _queryParams["page"] = page.toString();
                }
                if (pageLimit != null) {
                    _queryParams["page_limit"] = pageLimit.toString();
                }
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.TwelvelabsApiEnvironment.Default,
                        `knowledge-stores/${encodeURIComponent(knowledgeStoreId)}/item-collections/${encodeURIComponent(collectionId)}/items`,
                    ),
                    method: "GET",
                    headers: {
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "twelvelabs-js",
                        "X-Fern-SDK-Version": "1.3.4",
                        "User-Agent": "twelvelabs-js/1.3.4",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...(await this._getCustomAuthorizationHeaders()),
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    queryParameters: _queryParams,
                    requestType: "json",
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 600000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        data: serializers.KnowledgeStoreItemCollectionsListItemsResponse.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                        default:
                            throw new errors.TwelvelabsApiError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.TwelvelabsApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                            rawResponse: _response.rawResponse,
                        });
                    case "timeout":
                        throw new errors.TwelvelabsApiTimeoutError(
                            "Timeout exceeded when calling GET /knowledge-stores/{knowledge_store_id}/item-collections/{collection_id}/items.",
                        );
                    case "unknown":
                        throw new errors.TwelvelabsApiError({
                            message: _response.error.errorMessage,
                            rawResponse: _response.rawResponse,
                        });
                }
            },
        );
        let _offset = request?.page != null ? request?.page : 1;
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Pageable<
            TwelvelabsApi.KnowledgeStoreItemCollectionsListItemsResponse,
            TwelvelabsApi.KnowledgeStoreItem
        >({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) => (response?.data ?? []).length > 0,
            getItems: (response) => response?.data ?? [],
            loadPage: (_response) => {
                _offset += 1;
                return list(core.setObjectProperty(request, "page", _offset));
            },
        });
    }

    /**
     * Adds one or more items to the specified item collection. This operation is idempotent — items already in the collection are skipped. Every identifier must reference an existing item in the knowledge store.
     *
     * @param {string} knowledgeStoreId - The unique identifier of the knowledge store.
     * @param {string} collectionId - The unique identifier of the knowledge store item collection.
     * @param {TwelvelabsApi.KnowledgeStoreItemCollectionsAddItemsRequest} request
     * @param {KnowledgeStoreItemCollections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     *
     * @example
     *     await client.knowledgeStoreItemCollections.addItems("ks_069e9869-1ea3-7481-8000-dae72bf6be6e", "ksic_069e9870-3c4d-7abc-9012-3456789abcde", {
     *         itemIds: ["ksi_069e9870-3c4d-7abc-9012-3456789abcde"]
     *     })
     */
    public addItems(
        knowledgeStoreId: string,
        collectionId: string,
        request: TwelvelabsApi.KnowledgeStoreItemCollectionsAddItemsRequest,
        requestOptions?: KnowledgeStoreItemCollections.RequestOptions,
    ): core.HttpResponsePromise<TwelvelabsApi.KnowledgeStoreItemCollection> {
        return core.HttpResponsePromise.fromPromise(
            this.__addItems(knowledgeStoreId, collectionId, request, requestOptions),
        );
    }

    private async __addItems(
        knowledgeStoreId: string,
        collectionId: string,
        request: TwelvelabsApi.KnowledgeStoreItemCollectionsAddItemsRequest,
        requestOptions?: KnowledgeStoreItemCollections.RequestOptions,
    ): Promise<core.WithRawResponse<TwelvelabsApi.KnowledgeStoreItemCollection>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                `knowledge-stores/${encodeURIComponent(knowledgeStoreId)}/item-collections/${encodeURIComponent(collectionId)}/items/add`,
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.3.4",
                "User-Agent": "twelvelabs-js/1.3.4",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.KnowledgeStoreItemCollectionsAddItemsRequest.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 600000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.KnowledgeStoreItemCollection.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError(
                    "Timeout exceeded when calling POST /knowledge-stores/{knowledge_store_id}/item-collections/{collection_id}/items/add.",
                );
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Removes one or more items from the specified item collection. This operation is idempotent — identifiers that do not match a member of the collection are ignored. The items themselves remain in the knowledge store.
     *
     * @param {string} knowledgeStoreId - The unique identifier of the knowledge store.
     * @param {string} collectionId - The unique identifier of the knowledge store item collection.
     * @param {TwelvelabsApi.KnowledgeStoreItemCollectionsRemoveItemsRequest} request
     * @param {KnowledgeStoreItemCollections.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     *
     * @example
     *     await client.knowledgeStoreItemCollections.removeItems("ks_069e9869-1ea3-7481-8000-dae72bf6be6e", "ksic_069e9870-3c4d-7abc-9012-3456789abcde", {
     *         itemIds: ["ksi_069e9870-3c4d-7abc-9012-3456789abcde"]
     *     })
     */
    public removeItems(
        knowledgeStoreId: string,
        collectionId: string,
        request: TwelvelabsApi.KnowledgeStoreItemCollectionsRemoveItemsRequest,
        requestOptions?: KnowledgeStoreItemCollections.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(
            this.__removeItems(knowledgeStoreId, collectionId, request, requestOptions),
        );
    }

    private async __removeItems(
        knowledgeStoreId: string,
        collectionId: string,
        request: TwelvelabsApi.KnowledgeStoreItemCollectionsRemoveItemsRequest,
        requestOptions?: KnowledgeStoreItemCollections.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                `knowledge-stores/${encodeURIComponent(knowledgeStoreId)}/item-collections/${encodeURIComponent(collectionId)}/items/remove`,
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.3.4",
                "User-Agent": "twelvelabs-js/1.3.4",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.KnowledgeStoreItemCollectionsRemoveItemsRequest.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 600000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError(
                    "Timeout exceeded when calling POST /knowledge-stores/{knowledge_store_id}/item-collections/{collection_id}/items/remove.",
                );
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
