/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as TwelvelabsApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { Entity } from "../../../../../types/Entity";
import { PageInfo } from "../../../../../types/PageInfo";

export const EntitiesListByAssetResponse: core.serialization.ObjectSchema<
    serializers.entityCollections.EntitiesListByAssetResponse.Raw,
    TwelvelabsApi.entityCollections.EntitiesListByAssetResponse
> = core.serialization.object({
    data: core.serialization.list(Entity).optional(),
    pageInfo: core.serialization.property("page_info", PageInfo.optional()),
});

export declare namespace EntitiesListByAssetResponse {
    export interface Raw {
        data?: Entity.Raw[] | null;
        page_info?: PageInfo.Raw | null;
    }
}
