/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AssetsListRequestAssetTypesItem = "image" | "video" | "audio" | "document";
export const AssetsListRequestAssetTypesItem = {
    Image: "image",
    Video: "video",
    Audio: "audio",
    Document: "document",
} as const;
