/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as TwelvelabsApi from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { CreateEmbeddingsRequestInputType } from "../../types/CreateEmbeddingsRequestInputType";
import { TextInputRequest } from "../../../../../../types/TextInputRequest";
import { ImageInputRequest } from "../../../../../../types/ImageInputRequest";
import { TextImageInputRequest } from "../../../../../../types/TextImageInputRequest";
import { AudioInputRequest } from "../../../../../../types/AudioInputRequest";
import { VideoInputRequest } from "../../../../../../types/VideoInputRequest";

export const CreateEmbeddingsRequest: core.serialization.Schema<
    serializers.embed.CreateEmbeddingsRequest.Raw,
    TwelvelabsApi.embed.CreateEmbeddingsRequest
> = core.serialization.object({
    inputType: core.serialization.property("input_type", CreateEmbeddingsRequestInputType),
    modelName: core.serialization.property("model_name", core.serialization.string()),
    text: TextInputRequest.optional(),
    image: ImageInputRequest.optional(),
    textImage: core.serialization.property("text_image", TextImageInputRequest.optional()),
    audio: AudioInputRequest.optional(),
    video: VideoInputRequest.optional(),
});

export declare namespace CreateEmbeddingsRequest {
    export interface Raw {
        input_type: CreateEmbeddingsRequestInputType.Raw;
        model_name: string;
        text?: TextInputRequest.Raw | null;
        image?: ImageInputRequest.Raw | null;
        text_image?: TextImageInputRequest.Raw | null;
        audio?: AudioInputRequest.Raw | null;
        video?: VideoInputRequest.Raw | null;
    }
}
