/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as TwelvelabsApi from "../../../../api/index";
import * as core from "../../../../core";
import { EntityCollection } from "../../../types/EntityCollection";
import { PageInfo } from "../../../types/PageInfo";

export const EntityCollectionsListResponse: core.serialization.ObjectSchema<
    serializers.EntityCollectionsListResponse.Raw,
    TwelvelabsApi.EntityCollectionsListResponse
> = core.serialization.object({
    data: core.serialization.list(EntityCollection).optional(),
    pageInfo: core.serialization.property("page_info", PageInfo.optional()),
});

export declare namespace EntityCollectionsListResponse {
    export interface Raw {
        data?: EntityCollection.Raw[] | null;
        page_info?: PageInfo.Raw | null;
    }
}
