/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as TwelvelabsApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const IndexedAssetsListRequestUserMetadataValue: core.serialization.Schema<
    serializers.indexes.IndexedAssetsListRequestUserMetadataValue.Raw,
    TwelvelabsApi.indexes.IndexedAssetsListRequestUserMetadataValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.number(),
    core.serialization.boolean(),
]);

export declare namespace IndexedAssetsListRequestUserMetadataValue {
    export type Raw = string | number | boolean;
}
