/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The video understanding model to use. Only "marengo3.0" is supported.
 */
export type CreateEmbeddingsRequestModelName = "marengo3.0";
export const CreateEmbeddingsRequestModelName = {
    Marengo30: "marengo3.0",
} as const;
