/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of content for the embeddings.
 *
 * **Values**:
 * - `multi_input`: Text and up to 10 media sources, combined into a single embedding. To reference a specific media source from your text, use a placeholder in the following format: `<@name>`, where `name` matches the `name` field of a media source. Marengo 3.5 accepts images, video, and audio as media sources. Marengo 3.0 accepts images.
 * - `audio`: An audio file. Requires Marengo 3.0.
 * - `video`: A video file. Requires Marengo 3.0.
 * - `image`: An image file. Requires Marengo 3.0.
 * - `text`: Text input. Requires Marengo 3.0.
 * - `text_image`: Text and an image. Requires Marengo 3.0.
 */
export type CreateEmbeddingsRequestInputType = "text" | "image" | "text_image" | "audio" | "video" | "multi_input";
export const CreateEmbeddingsRequestInputType = {
    Text: "text",
    Image: "image",
    TextImage: "text_image",
    Audio: "audio",
    Video: "video",
    MultiInput: "multi_input",
} as const;
