/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of asset you want to upload.
 */
export type CreateAssetUploadRequestType = "video" | "audio" | "image";
export const CreateAssetUploadRequestType = {
    Video: "video",
    Audio: "audio",
    Image: "image",
} as const;
