/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The video understanding model to enable for this index.
 * - `marengo3.0`: Enhanced model with sports intelligence and extended content support.
 *
 * <Note title="Note">
 * You cannot change the model configuration once the index has been created.
 * </Note>
 */
export type IndexesCreateRequestModelsItemModelName = "marengo3.0";
export const IndexesCreateRequestModelsItemModelName = {
    Marengo30: "marengo3.0",
} as const;
