/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../index";

export interface IndexesCreateRequestModelsItem {
    /**
     * The video understanding model to enable for this index.
     * - `marengo3.0`: Enhanced model with sports intelligence and extended content support.
     *
     * <Note title="Note">
     * You cannot change the model configuration once the index has been created.
     * </Note>
     */
    modelName: TwelvelabsApi.IndexesCreateRequestModelsItemModelName;
    /** An array that specifies which modalities the platform analyzes. For the Marengo model, you can specify one or both of the following model options: `visual` and `audio`. For more details, see the [Model options](/v1.3/docs/concepts/modalities#model-options) section. */
    modelOptions: string[];
}
