/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IndexesCreateResponse {
    /** Represents the unique identifier of the `index` object. */
    id?: string;
}
