/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../../index";

/**
 * @example
 *     {
 *         page: 1,
 *         pageLimit: 10
 *     }
 */
export interface AssetsListRequest {
    /**
     * A number that identifies the page to retrieve.
     *
     * **Default**: `1`.
     */
    page?: number;
    /**
     * The number of items to return on each page.
     *
     * **Default**: `10`.
     * **Max**: `50`.
     */
    pageLimit?: number;
    /**
     * Filters the response to include only assets with the specified IDs. Provide one or more asset IDs. When you specify multiple IDs, the platform returns all matching assets.
     */
    assetIds?: string | string[];
    /**
     * Filters the response to include only assets of the specified types. Provide one or more asset types. When you specify multiple types, the platform returns all matching assets.
     */
    assetTypes?: TwelvelabsApi.AssetsListRequestAssetTypesItem | TwelvelabsApi.AssetsListRequestAssetTypesItem[];
}
