/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../../index";
import * as fs from "fs";

/**
 * @example
 *     {
 *         method: "direct"
 *     }
 */
export interface AssetsCreateRequest {
    /** Specifies the upload method for the asset. Use `direct` to upload a local file or `url` for a publicly accessible URL. */
    method: TwelvelabsApi.AssetsCreateRequestMethod;
    file?: File | fs.ReadStream | Blob | undefined;
    /**
     * Specify this parameter to upload a file from a publicly accessible URL. This parameter is required when `method` is set to `url`.
     *
     * URL uploads have a maximum limit of 4 GB.
     */
    url?: string;
    /** The optional filename of the asset. If not provided, the platform will determine the filename from the file or URL. */
    filename?: string;
    /**
     * When set to `true`, the platform generates an HLS playlist and segments for streaming. Applicable to video and audio assets only.
     *
     * **Default**: `false`.
     */
    enableHls?: boolean;
    /**
     * When set to `true`, the platform generates thumbnail images from the uploaded content.
     *
     * **Default**: `false`.
     */
    enableThumbnail?: boolean;
}
