/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as TwelvelabsApi from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const TransfersCreateRequest: core.serialization.Schema<
    serializers.tasks.TransfersCreateRequest.Raw,
    TwelvelabsApi.tasks.TransfersCreateRequest
> = core.serialization.object({
    indexId: core.serialization.property("index_id", core.serialization.string()),
    incrementalImport: core.serialization.property("incremental_import", core.serialization.boolean().optional()),
    retryFailed: core.serialization.property("retry_failed", core.serialization.boolean().optional()),
    userMetadata: core.serialization.property(
        "user_metadata",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    ),
});

export declare namespace TransfersCreateRequest {
    export interface Raw {
        index_id: string;
        incremental_import?: boolean | null;
        retry_failed?: boolean | null;
        user_metadata?: Record<string, unknown> | null;
    }
}
