/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         redirectUri: "https://app.example.com/oauth/done"
 *     }
 */
export interface CreateRedirectUriRequest {
    /** The redirect URI to register. Must use HTTPS, resolve to a public host, and contain no wildcards. Register it exactly as your application sends it, because the authorization flow requires an exact match. */
    redirectUri: string;
}
