/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         page: 1,
 *         pageLimit: 10
 *     }
 */
export interface MultipartUploadListIncompleteUploadsRequest {
    /**
     * A number that identifies the page to retrieve.
     *
     * **Default**: `1`.
     */
    page?: number;
    /**
     * The number of items to return on each page.
     *
     * **Default**: `10`.
     * **Max**: `50`.
     */
    pageLimit?: number;
}
