/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as TwelvelabsApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { VideoVector } from "../../../../../types/VideoVector";
import { PageInfo } from "../../../../../types/PageInfo";

export const VideosListResponse: core.serialization.ObjectSchema<
    serializers.indexes.VideosListResponse.Raw,
    TwelvelabsApi.indexes.VideosListResponse
> = core.serialization.object({
    data: core.serialization.list(VideoVector).optional(),
    pageInfo: core.serialization.property("page_info", PageInfo.optional()),
});

export declare namespace VideosListResponse {
    export interface Raw {
        data?: VideoVector.Raw[] | null;
        page_info?: PageInfo.Raw | null;
    }
}
