/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as TwelvelabsApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const VideosRetrieveRequestEmbeddingOptionItem: core.serialization.Schema<
    serializers.indexes.VideosRetrieveRequestEmbeddingOptionItem.Raw,
    TwelvelabsApi.indexes.VideosRetrieveRequestEmbeddingOptionItem
> = core.serialization.enum_(["visual-text", "audio"]);

export declare namespace VideosRetrieveRequestEmbeddingOptionItem {
    export type Raw = "visual-text" | "audio";
}
