/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../../../index";

export interface EntitiesListResponse {
    /** An array containing the entities. */
    data?: TwelvelabsApi.Entity[];
    pageInfo?: TwelvelabsApi.PageInfo;
}
