/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as TwelvelabsApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const CreateAnalyzeBatchRequestAnalysisMode: core.serialization.Schema<
    serializers.analyzeAsync.CreateAnalyzeBatchRequestAnalysisMode.Raw,
    TwelvelabsApi.analyzeAsync.CreateAnalyzeBatchRequestAnalysisMode
> = core.serialization.enum_(["general", "time_based_metadata"]);

export declare namespace CreateAnalyzeBatchRequestAnalysisMode {
    export type Raw = "general" | "time_based_metadata";
}
