/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as TwelvelabsApi from "../../../../../../../api/index";
import * as core from "../../../../../../../core";
import { CreateAnalyzeBatchRequestModelName } from "../../types/CreateAnalyzeBatchRequestModelName";
import { CreateAnalyzeBatchRequestAnalysisMode } from "../../types/CreateAnalyzeBatchRequestAnalysisMode";
import { BatchDefaults } from "../../../../../../types/BatchDefaults";
import { BatchItemRequest } from "../../../../../../types/BatchItemRequest";

export const CreateAnalyzeBatchRequest: core.serialization.Schema<
    serializers.analyzeAsync.CreateAnalyzeBatchRequest.Raw,
    TwelvelabsApi.analyzeAsync.CreateAnalyzeBatchRequest
> = core.serialization.object({
    modelName: core.serialization.property("model_name", CreateAnalyzeBatchRequestModelName),
    analysisMode: core.serialization.property("analysis_mode", CreateAnalyzeBatchRequestAnalysisMode),
    defaults: BatchDefaults.optional(),
    requests: core.serialization.list(BatchItemRequest),
});

export declare namespace CreateAnalyzeBatchRequest {
    export interface Raw {
        model_name: CreateAnalyzeBatchRequestModelName.Raw;
        analysis_mode: CreateAnalyzeBatchRequestAnalysisMode.Raw;
        defaults?: BatchDefaults.Raw | null;
        requests: BatchItemRequest.Raw[];
    }
}
