/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as TwelvelabsApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const TasksCreateRequestVideoEmbeddingScopeItem: core.serialization.Schema<
    serializers.embed.TasksCreateRequestVideoEmbeddingScopeItem.Raw,
    TwelvelabsApi.embed.TasksCreateRequestVideoEmbeddingScopeItem
> = core.serialization.enum_(["clip", "video"]);

export declare namespace TasksCreateRequestVideoEmbeddingScopeItem {
    export type Raw = "clip" | "video";
}
