/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as TwelvelabsApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const TasksCreateResponse: core.serialization.ObjectSchema<
    serializers.embed.TasksCreateResponse.Raw,
    TwelvelabsApi.embed.TasksCreateResponse
> = core.serialization.object({
    id: core.serialization.property("_id", core.serialization.string().optional()),
});

export declare namespace TasksCreateResponse {
    export interface Raw {
        _id?: string | null;
    }
}
