/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as TwelvelabsApi from "../../../../../../api/index";
import * as core from "../../../../../../core";
import { TasksRetrieveResponseVideoEmbedding } from "./TasksRetrieveResponseVideoEmbedding";

export const TasksRetrieveResponse: core.serialization.ObjectSchema<
    serializers.embed.TasksRetrieveResponse.Raw,
    TwelvelabsApi.embed.TasksRetrieveResponse
> = core.serialization.object({
    videoEmbedding: core.serialization.property("video_embedding", TasksRetrieveResponseVideoEmbedding.optional()),
    id: core.serialization.property("_id", core.serialization.string().optional()),
    modelName: core.serialization.property("model_name", core.serialization.string().optional()),
    status: core.serialization.string().optional(),
    createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
});

export declare namespace TasksRetrieveResponse {
    export interface Raw {
        video_embedding?: TasksRetrieveResponseVideoEmbedding.Raw | null;
        _id?: string | null;
        model_name?: string | null;
        status?: string | null;
        created_at?: string | null;
    }
}
