/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as TwelvelabsApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const TransfersCreateResponseFailedFilesItem: core.serialization.ObjectSchema<
    serializers.tasks.TransfersCreateResponseFailedFilesItem.Raw,
    TwelvelabsApi.tasks.TransfersCreateResponseFailedFilesItem
> = core.serialization.object({
    filename: core.serialization.string().optional(),
    errorMessage: core.serialization.property("error_message", core.serialization.string().optional()),
});

export declare namespace TransfersCreateResponseFailedFilesItem {
    export interface Raw {
        filename?: string | null;
        error_message?: string | null;
    }
}
