/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../index";
import * as TwelvelabsApi from "../../../../../../api/index";
import * as core from "../../../../../../core";

export const TransfersCreateResponseVideosItem: core.serialization.ObjectSchema<
    serializers.tasks.TransfersCreateResponseVideosItem.Raw,
    TwelvelabsApi.tasks.TransfersCreateResponseVideosItem
> = core.serialization.object({
    videoId: core.serialization.property("video_id", core.serialization.string().optional()),
    filename: core.serialization.string().optional(),
});

export declare namespace TransfersCreateResponseVideosItem {
    export interface Raw {
        video_id?: string | null;
        filename?: string | null;
    }
}
