/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The model you wish to use. Only `"marengo3.0"` is supported.
 */
export type CreateAsyncEmbeddingRequestModelName = "marengo3.0";
export const CreateAsyncEmbeddingRequestModelName = {
    Marengo30: "marengo3.0",
} as const;
