/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of content for which you wish to create embeddings.
 *
 * **Values**:
 * - `audio`: Audio files
 * - `video`: Video content
 */
export type CreateAsyncEmbeddingRequestInputType = "audio" | "video";
export const CreateAsyncEmbeddingRequestInputType = {
    Audio: "audio",
    Video: "video",
} as const;
