/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../../../index";

export interface TransfersGetLogsResponse {
    /** An array that contains the import logs. */
    data?: TwelvelabsApi.ImportLog[];
}
