/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../../../index";

export interface TransfersCreateResponse {
    /** A list of the video files that failed to import. Typically, these files did not meet the upload requirements. To resolve this, review the requirements listed in the [Prerequisites](/v1.3/docs/guides/search#prerequisites) section of the **Search** page. */
    failedFiles?: TwelvelabsApi.tasks.TransfersCreateResponseFailedFilesItem[];
    /** A list of the videos that will be uploaded and indexed. */
    videos?: TwelvelabsApi.tasks.TransfersCreateResponseVideosItem[];
}
