/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as TwelvelabsApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { CreateAssetUploadRequestType } from "../../types/CreateAssetUploadRequestType";

export const CreateAssetUploadRequest: core.serialization.Schema<
    serializers.CreateAssetUploadRequest.Raw,
    TwelvelabsApi.CreateAssetUploadRequest
> = core.serialization.object({
    filename: core.serialization.string(),
    type: CreateAssetUploadRequestType,
    totalSize: core.serialization.property("total_size", core.serialization.number()),
    enableHls: core.serialization.property("enable_hls", core.serialization.boolean().optional()),
    enableThumbnail: core.serialization.property("enable_thumbnail", core.serialization.boolean().optional()),
});

export declare namespace CreateAssetUploadRequest {
    export interface Raw {
        filename: string;
        type: CreateAssetUploadRequestType.Raw;
        total_size: number;
        enable_hls?: boolean | null;
        enable_thumbnail?: boolean | null;
    }
}
