/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../../../../index";

/**
 * @example
 *     {
 *         page: 1,
 *         pageLimit: 10,
 *         status: "queued",
 *         videoUrl: "https://example.com/video.mp4",
 *         assetId: "69abc123def456789012abcd",
 *         analysisMode: "time_based_metadata"
 *     }
 *
 * @example
 *     {
 *         page: 1,
 *         pageLimit: 10,
 *         status: "queued",
 *         videoUrl: "https://example.com/video.mp4",
 *         assetId: "69abc123def456789012abcd",
 *         analysisMode: "time_based_metadata"
 *     }
 */
export interface TasksListRequest {
    /**
     * A number that identifies the page to retrieve.
     *
     * **Default**: `1`.
     */
    page?: number;
    /**
     * The number of items to return on each page.
     *
     * **Default**: `10`.
     * **Max**: `50`.
     */
    pageLimit?: number;
    /**
     * Filter analysis tasks by status.
     * Possible values: `queued`, `pending`, `processing`, `ready`, `failed`.
     */
    status?: TwelvelabsApi.AnalyzeTaskStatus;
    /**
     * Filter tasks by exact video source URL.
     */
    videoUrl?: string;
    /**
     * Filter tasks by asset ID.
     */
    assetId?: string;
    /**
     * Filter tasks by the analysis mode used when creating the task.
     */
    analysisMode?: TwelvelabsApi.analyzeAsync.TasksListRequestAnalysisMode;
}
