/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SearchCreateRequestSearchOptionsItem = "visual" | "audio";
export const SearchCreateRequestSearchOptionsItem = {
    Visual: "visual",
    Audio: "audio",
} as const;
