/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Combines multiple search options using `or` or `and`. Use `and` to find segments matching all search options. Use `or` to find segments matching any search option.
 *
 *   **Default**: `or`.
 */
export type SearchCreateRequestOperator = "or" | "and";
export const SearchCreateRequestOperator = {
    Or: "or",
    And: "and",
} as const;
