/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as TwelvelabsApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const CreateRedirectUriRequest: core.serialization.Schema<
    serializers.CreateRedirectUriRequest.Raw,
    TwelvelabsApi.CreateRedirectUriRequest
> = core.serialization.object({
    redirectUri: core.serialization.property("redirect_uri", core.serialization.string()),
});

export declare namespace CreateRedirectUriRequest {
    export interface Raw {
        redirect_uri: string;
    }
}
