/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as TwelvelabsApi from "../../../../api/index";
import * as core from "../../../../core";

export const TasksListRequestStatusItem: core.serialization.Schema<
    serializers.TasksListRequestStatusItem.Raw,
    TwelvelabsApi.TasksListRequestStatusItem
> = core.serialization.enum_(["ready", "uploading", "validating", "pending", "queued", "indexing", "failed"]);

export declare namespace TasksListRequestStatusItem {
    export type Raw = "ready" | "uploading" | "validating" | "pending" | "queued" | "indexing" | "failed";
}
