/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../index";

export interface ListAllEntitiesResponse {
    /** An array containing the entities. */
    data?: TwelvelabsApi.InternalEntity[];
    pageInfo?: TwelvelabsApi.PageInfo;
}
