/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as TwelvelabsApi from "../../../api/index";
import * as core from "../../../core";
import { VideoContext } from "../../types/VideoContext";
import { AnalyzeTextPrompt } from "../../types/AnalyzeTextPrompt";
import { AnalyzeTemperature } from "../../types/AnalyzeTemperature";
import { SyncResponseFormat } from "../../types/SyncResponseFormat";
import { AnalyzeMaxTokens } from "../../types/AnalyzeMaxTokens";

export const AnalyzeStreamRequest: core.serialization.Schema<
    serializers.AnalyzeStreamRequest.Raw,
    TwelvelabsApi.AnalyzeStreamRequest
> = core.serialization.object({
    videoId: core.serialization.property("video_id", core.serialization.string().optional()),
    video: VideoContext.optional(),
    prompt: AnalyzeTextPrompt,
    temperature: AnalyzeTemperature.optional(),
    responseFormat: core.serialization.property("response_format", SyncResponseFormat.optional()),
    maxTokens: core.serialization.property("max_tokens", AnalyzeMaxTokens.optional()),
});

export declare namespace AnalyzeStreamRequest {
    export interface Raw {
        video_id?: string | null;
        video?: VideoContext.Raw | null;
        prompt: AnalyzeTextPrompt.Raw;
        temperature?: AnalyzeTemperature.Raw | null;
        response_format?: SyncResponseFormat.Raw | null;
        max_tokens?: AnalyzeMaxTokens.Raw | null;
    }
}
