/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as TwelvelabsApi from "../../../api/index";
import * as core from "../../../core";
import { ResponseFormat } from "../../types/ResponseFormat";

export const AnalyzeStreamRequest: core.serialization.Schema<
    serializers.AnalyzeStreamRequest.Raw,
    TwelvelabsApi.AnalyzeStreamRequest
> = core.serialization.object({
    videoId: core.serialization.property("video_id", core.serialization.string()),
    prompt: core.serialization.string(),
    temperature: core.serialization.number().optional(),
    responseFormat: core.serialization.property("response_format", ResponseFormat.optional()),
    maxTokens: core.serialization.property("max_tokens", core.serialization.number().optional()),
});

export declare namespace AnalyzeStreamRequest {
    export interface Raw {
        video_id: string;
        prompt: string;
        temperature?: number | null;
        response_format?: ResponseFormat.Raw | null;
        max_tokens?: number | null;
    }
}
