/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as TwelvelabsApi from "../../../api/index";
import * as core from "../../../core";

export const GenerateRequest: core.serialization.Schema<
    serializers.GenerateRequest.Raw,
    TwelvelabsApi.GenerateRequest
> = core.serialization.object({
    videoId: core.serialization.property("video_id", core.serialization.string()),
    prompt: core.serialization.string(),
    temperature: core.serialization.number().optional(),
    stream: core.serialization.boolean().optional(),
});

export declare namespace GenerateRequest {
    export interface Raw {
        video_id: string;
        prompt: string;
        temperature?: number | null;
        stream?: boolean | null;
    }
}
