/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as TwelvelabsApi from "../../../../../index";
import * as serializers from "../../../../../../serialization/index";
import urlJoin from "url-join";
import * as errors from "../../../../../../errors/index";
import * as stream from "stream";

export declare namespace Batches {
    export interface Options {
        environment?: core.Supplier<environments.TwelvelabsApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Batches {
    constructor(protected readonly _options: Batches.Options) {}

    /**
     * Use this method to list all the batch objects in your account. The response sorts batches by creation date, with the newest batch first.
     *
     * @param {TwelvelabsApi.analyzeAsync.BatchesListRequest} request
     * @param {Batches.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     *
     * @example
     *     await client.analyzeAsync.batches.list({
     *         page: 1,
     *         pageLimit: 10
     *     })
     */
    public async list(
        request: TwelvelabsApi.analyzeAsync.BatchesListRequest = {},
        requestOptions?: Batches.RequestOptions,
    ): Promise<core.Page<TwelvelabsApi.AnalyzeBatchStatusResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TwelvelabsApi.analyzeAsync.BatchesListRequest,
            ): Promise<core.WithRawResponse<TwelvelabsApi.analyzeAsync.BatchesListResponse>> => {
                const { page, pageLimit, status, analysisMode } = request;
                const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
                if (page != null) {
                    _queryParams["page"] = page.toString();
                }
                if (pageLimit != null) {
                    _queryParams["page_limit"] = pageLimit.toString();
                }
                if (status != null) {
                    if (Array.isArray(status)) {
                        _queryParams["status"] = status.map((item) =>
                            serializers.BatchStatus.jsonOrThrow(item, { unrecognizedObjectKeys: "strip" }),
                        );
                    } else {
                        _queryParams["status"] = serializers.BatchStatus.jsonOrThrow(status, {
                            unrecognizedObjectKeys: "strip",
                        });
                    }
                }
                if (analysisMode != null) {
                    if (Array.isArray(analysisMode)) {
                        _queryParams["analysis_mode"] = analysisMode.map((item) =>
                            serializers.analyzeAsync.BatchesListRequestAnalysisModeItem.jsonOrThrow(item, {
                                unrecognizedObjectKeys: "strip",
                            }),
                        );
                    } else {
                        _queryParams["analysis_mode"] =
                            serializers.analyzeAsync.BatchesListRequestAnalysisModeItem.jsonOrThrow(analysisMode, {
                                unrecognizedObjectKeys: "strip",
                            });
                    }
                }
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.TwelvelabsApiEnvironment.Default,
                        "analyze/batches",
                    ),
                    method: "GET",
                    headers: {
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "twelvelabs-js",
                        "X-Fern-SDK-Version": "1.2.8",
                        "User-Agent": "twelvelabs-js/1.2.8",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...(await this._getCustomAuthorizationHeaders()),
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    queryParameters: _queryParams,
                    requestType: "json",
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 600000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        data: serializers.analyzeAsync.BatchesListResponse.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                        default:
                            throw new errors.TwelvelabsApiError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.TwelvelabsApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                            rawResponse: _response.rawResponse,
                        });
                    case "timeout":
                        throw new errors.TwelvelabsApiTimeoutError(
                            "Timeout exceeded when calling GET /analyze/batches.",
                        );
                    case "unknown":
                        throw new errors.TwelvelabsApiError({
                            message: _response.error.errorMessage,
                            rawResponse: _response.rawResponse,
                        });
                }
            },
        );
        let _offset = request?.page != null ? request?.page : 1;
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Pageable<
            TwelvelabsApi.analyzeAsync.BatchesListResponse,
            TwelvelabsApi.AnalyzeBatchStatusResponse
        >({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) => (response?.data ?? []).length > 0,
            getItems: (response) => response?.data ?? [],
            loadPage: (_response) => {
                _offset += 1;
                return list(core.setObjectProperty(request, "page", _offset));
            },
        });
    }

    /**
     * Use this method to submit many video analysis requests in a single call. Each request creates an analysis task. The response contains one batch identifier and one task identifier per request. Use the batch identifier to check progress and retrieve results.
     *
     * <Note title="Model requirement">
     * You must use Pegasus 1.5 for batch analysis. Set the `model_name` parameter to `pegasus1.5`.
     * </Note>
     *
     * **When to use this method**:
     * - Run the same model and analysis settings across many videos.
     * - Track a single batch instead of many individual analysis tasks.
     *
     * **Do not use this method for**:
     * - Single videos that require immediate results. Use the [`POST`](/v1.3/api-reference/analyze-videos/sync-analysis) method of the `/analyze` endpoint instead.
     * - Background processing of a single video. Use the [`POST`](/v1.3/api-reference/analyze-videos/create-async-analysis-task) method of the `/analyze/tasks` endpoint instead.
     *
     * **Retention and retry**:
     * - Batches expire 24 hours after creation. You can retrieve results for 30 days after creation.
     * - If processing does not finish for some items in time, resubmit them in a new batch.
     *
     * **Limits**:
     * - Up to 1,000 requests per batch.
     * - Up to 2,000 total content hours per batch.
     * - Up to 5 active batches per account.
     *
     * @param {TwelvelabsApi.analyzeAsync.CreateAnalyzeBatchRequest} request
     * @param {Batches.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     * @throws {@link TwelvelabsApi.NotFoundError}
     * @throws {@link TwelvelabsApi.ConflictError}
     * @throws {@link TwelvelabsApi.TooManyRequestsError}
     * @throws {@link TwelvelabsApi.ServiceUnavailableError}
     * @throws {@link TwelvelabsApi.GatewayTimeoutError}
     *
     * @example
     *     await client.analyzeAsync.batches.create({
     *         modelName: "pegasus1.5",
     *         analysisMode: "general",
     *         defaults: {
     *             prompt: {
     *                 inputText: "Generate a 3-sentence executive summary of this video."
     *             },
     *             temperature: 0.2,
     *             maxTokens: 4096
     *         },
     *         requests: [{
     *                 video: {
     *                     type: "asset_id",
     *                     assetId: "6298d673f1090f1100476d4c"
     *                 },
     *                 customId: "summary-001"
     *             }, {
     *                 video: {
     *                     type: "asset_id",
     *                     assetId: "6298d673f1090f1100476d4d"
     *                 },
     *                 customId: "summary-002"
     *             }, {
     *                 video: {
     *                     type: "asset_id",
     *                     assetId: "6298d673f1090f1100476d4e"
     *                 },
     *                 customId: "action-003",
     *                 prompt: {
     *                     inputText: "List all action items discussed."
     *                 }
     *             }]
     *     })
     *
     * @example
     *     await client.analyzeAsync.batches.create({
     *         modelName: "pegasus1.5",
     *         analysisMode: "time_based_metadata",
     *         defaults: {
     *             responseFormat: {
     *                 type: "segment_definitions",
     *                 segmentDefinitions: [{
     *                         id: "product_moments",
     *                         description: "Moments where a person holds <@product> while speaking to the camera.",
     *                         fields: [{
     *                                 name: "segment_title",
     *                                 type: "string",
     *                                 description: "A short headline for this moment"
     *                             }, {
     *                                 name: "product_visibility",
     *                                 type: "string",
     *                                 description: "How prominently the product appears in this segment",
     *                                 enum: ["FULL", "PARTIAL", "BACKGROUND"]
     *                             }],
     *                         mediaSources: [{
     *                                 name: "product",
     *                                 mediaType: "image",
     *                                 url: "https://example.com/product.jpg"
     *                             }]
     *                     }]
     *             },
     *             temperature: 0,
     *             maxTokens: 4096,
     *             minSegmentDuration: 2
     *         },
     *         requests: [{
     *                 video: {
     *                     type: "asset_id",
     *                     assetId: "6298d673f1090f1100476d4c"
     *                 },
     *                 customId: "ep-001"
     *             }, {
     *                 video: {
     *                     type: "asset_id",
     *                     assetId: "6298d673f1090f1100476d4d"
     *                 },
     *                 customId: "ep-002"
     *             }]
     *     })
     */
    public create(
        request: TwelvelabsApi.analyzeAsync.CreateAnalyzeBatchRequest,
        requestOptions?: Batches.RequestOptions,
    ): core.HttpResponsePromise<TwelvelabsApi.CreateAnalyzeBatchResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: TwelvelabsApi.analyzeAsync.CreateAnalyzeBatchRequest,
        requestOptions?: Batches.RequestOptions,
    ): Promise<core.WithRawResponse<TwelvelabsApi.CreateAnalyzeBatchResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                "analyze/batches",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.2.8",
                "User-Agent": "twelvelabs-js/1.2.8",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.analyzeAsync.CreateAnalyzeBatchRequest.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 600000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.CreateAnalyzeBatchResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new TwelvelabsApi.NotFoundError(_response.error.body, _response.rawResponse);
                case 409:
                    throw new TwelvelabsApi.ConflictError(_response.error.body, _response.rawResponse);
                case 429:
                    throw new TwelvelabsApi.TooManyRequestsError(_response.error.body, _response.rawResponse);
                case 503:
                    throw new TwelvelabsApi.ServiceUnavailableError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 504:
                    throw new TwelvelabsApi.GatewayTimeoutError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError("Timeout exceeded when calling POST /analyze/batches.");
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Use this method to monitor a batch. The response includes the current batch status and counts for queued, processing, ready, failed, and canceled items.
     *
     * Poll this method until the batch reaches the `completed`, `canceled`, or `expired` status. To retrieve the results, call the [`GET`](/v1.3/api-reference/analyze-videos/batch-analysis/retrieve-batch-results) method of the `/analyze/batches/{batch_id}/results` endpoint.
     *
     * Do not treat the `completed` status as a success signal. It means processing has finished for every item, not that every analysis succeeded. To see how many items succeeded, failed, or were canceled, check the `ready_items`, `failed_items`, and `canceled_items` fields. A batch never has the `failed` status.
     *
     * @param {string} batchId - The unique identifier of the batch.
     * @param {Batches.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.NotFoundError}
     *
     * @example
     *     await client.analyzeAsync.batches.retrieve("68f4ddaf8aaa60d33df0e800")
     */
    public retrieve(
        batchId: string,
        requestOptions?: Batches.RequestOptions,
    ): core.HttpResponsePromise<TwelvelabsApi.AnalyzeBatchStatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(batchId, requestOptions));
    }

    private async __retrieve(
        batchId: string,
        requestOptions?: Batches.RequestOptions,
    ): Promise<core.WithRawResponse<TwelvelabsApi.AnalyzeBatchStatusResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                `analyze/batches/${encodeURIComponent(batchId)}`,
            ),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.2.8",
                "User-Agent": "twelvelabs-js/1.2.8",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 600000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.AnalyzeBatchStatusResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new TwelvelabsApi.NotFoundError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError(
                    "Timeout exceeded when calling GET /analyze/batches/{batch_id}.",
                );
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Use this method to delete a batch and all the tasks associated with it. You can only delete batches with status `completed`, `canceled`, or `expired`.
     *
     * Deleting a batch does not affect billing. You are billed for every completed analysis regardless of whether you delete the batch afterward.
     *
     * To stop a batch with the `pending` or `processing` status, use the [`POST`](/v1.3/api-reference/analyze-videos/batch-analysis/cancel-batch) method of the `/analyze/batches/{batch_id}/cancel` endpoint.
     *
     * Batches are deleted 30 days after creation.
     *
     * @param {string} batchId - The unique identifier of the batch.
     * @param {Batches.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.NotFoundError}
     * @throws {@link TwelvelabsApi.ConflictError}
     *
     * @example
     *     await client.analyzeAsync.batches.delete("68f4ddaf8aaa60d33df0e800")
     */
    public delete(batchId: string, requestOptions?: Batches.RequestOptions): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(batchId, requestOptions));
    }

    private async __delete(
        batchId: string,
        requestOptions?: Batches.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                `analyze/batches/${encodeURIComponent(batchId)}`,
            ),
            method: "DELETE",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.2.8",
                "User-Agent": "twelvelabs-js/1.2.8",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 600000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new TwelvelabsApi.NotFoundError(_response.error.body, _response.rawResponse);
                case 409:
                    throw new TwelvelabsApi.ConflictError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError(
                    "Timeout exceeded when calling DELETE /analyze/batches/{batch_id}.",
                );
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Use this method to retrieve the results for each item in a batch. You can call it while the batch has the `pending` or `processing` status.
     *
     * Each result entry has a status. For details on each status, see the [Item statuses](/v1.3/api-reference/analyze-videos/batch-analysis/the-batch-object#item-statuses) section on the **The batch object** page.
     *
     * Each result entry includes a task identifier in the `task_id` field. Use this value with the [`GET`](/v1.3/api-reference/analyze-videos/retrieve-analysis-task-status-results) method of the `/analyze/tasks/{task_id}` endpoint if you need the full analysis task response.
     *
     * You can retrieve results for 30 days after batch creation.
     */
    public results(
        batchId: string,
        requestOptions?: Batches.RequestOptions,
    ): core.HttpResponsePromise<core.Stream<TwelvelabsApi.BatchResultItem>> {
        return core.HttpResponsePromise.fromPromise(this.__results(batchId, requestOptions));
    }

    private async __results(
        batchId: string,
        requestOptions?: Batches.RequestOptions,
    ): Promise<core.WithRawResponse<core.Stream<TwelvelabsApi.BatchResultItem>>> {
        const _response = await core.fetcher<stream.Readable>({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                `analyze/batches/${encodeURIComponent(batchId)}/results`,
            ),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.2.8",
                "User-Agent": "twelvelabs-js/1.2.8",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            responseType: "sse",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 600000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: new core.Stream({
                    stream: _response.body,
                    parse: async (data) => {
                        return serializers.BatchResultItem.parseOrThrow(data, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        });
                    },
                    signal: requestOptions?.abortSignal,
                    eventShape: {
                        type: "json",
                        messageTerminator: "\n",
                    },
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new TwelvelabsApi.NotFoundError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError(
                    "Timeout exceeded when calling GET /analyze/batches/{batch_id}/results.",
                );
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Use this method to request cancellation for a batch with the `pending` or `processing` status.
     *
     * When you invoke this method, the platform performs the following steps:
     * - Cancels the items in the `queued` status.
     * - Finishes the analysis for the items in the `processing` status.
     *
     * The batch status changes to `canceling` immediately, and to `canceled` after every item reaches `ready`, `failed`, or `canceled`. You are not billed for canceled or failed items.
     *
     * @param {string} batchId - The unique identifier of the batch.
     * @param {Batches.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.NotFoundError}
     * @throws {@link TwelvelabsApi.ConflictError}
     *
     * @example
     *     await client.analyzeAsync.batches.cancel("68f4ddaf8aaa60d33df0e800")
     */
    public cancel(
        batchId: string,
        requestOptions?: Batches.RequestOptions,
    ): core.HttpResponsePromise<TwelvelabsApi.AnalyzeBatchStatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__cancel(batchId, requestOptions));
    }

    private async __cancel(
        batchId: string,
        requestOptions?: Batches.RequestOptions,
    ): Promise<core.WithRawResponse<TwelvelabsApi.AnalyzeBatchStatusResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                `analyze/batches/${encodeURIComponent(batchId)}/cancel`,
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.2.8",
                "User-Agent": "twelvelabs-js/1.2.8",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 600000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.AnalyzeBatchStatusResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new TwelvelabsApi.NotFoundError(_response.error.body, _response.rawResponse);
                case 409:
                    throw new TwelvelabsApi.ConflictError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError(
                    "Timeout exceeded when calling POST /analyze/batches/{batch_id}/cancel.",
                );
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
