/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * System-generated metadata about the video.
 */
export interface VideosRetrieveResponseSystemMetadata {
    duration?: number;
    filename?: string;
    fps?: number;
    height?: number;
    width?: number;
}
