/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VideosRetrieveRequestEmbeddingOptionItem = "visual" | "audio" | "transcription" | "visual-text";
export const VideosRetrieveRequestEmbeddingOptionItem = {
    Visual: "visual",
    Audio: "audio",
    Transcription: "transcription",
    VisualText: "visual-text",
} as const;
