/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as TwelvelabsApi from "../../../../api/index";
import * as core from "../../../../core";

export const KnowledgeStoresListRequestSortBy: core.serialization.Schema<
    serializers.KnowledgeStoresListRequestSortBy.Raw,
    TwelvelabsApi.KnowledgeStoresListRequestSortBy
> = core.serialization.enum_(["created_at", "updated_at"]);

export declare namespace KnowledgeStoresListRequestSortBy {
    export type Raw = "created_at" | "updated_at";
}
