/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../../../index";

export interface TasksListResponse {
    /** An array that contains up to `page_limit` analysis tasks. */
    data: TwelvelabsApi.AnalyzeTaskResponse[];
    pageInfo: TwelvelabsApi.PageInfo;
}
