/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * A batch object that summarizes the batch.
 */
export interface AnalyzeBatchSummary {
    /** The unique identifier of the batch. Use this value to retrieve the batch status or results. */
    batchId: string;
    /** The analysis mode applied to every item in this batch. */
    analysisMode: TwelvelabsApi.AnalyzeBatchSummaryAnalysisMode;
    /** The model used for every item in this batch. */
    modelName: string;
    status: TwelvelabsApi.BatchStatus;
    /** The number of items submitted in the batch. */
    totalItems: number;
    /** The date and time, in the RFC 3339 format, when the batch was created. */
    createdAt: Date;
    /** The date and time, in the RFC 3339 format, when the batch expires (the `created_at` field value plus 24 hours). Unfinished items at expiration are canceled. Items that finished before then remain retrievable for 30 days after creation, when the batch and its results are deleted. */
    expiresAt: Date;
    /** The date and time, in the RFC 3339 format, when the batch status became `completed`. Present only when the status is `completed`. */
    completedAt?: Date;
    /** The date and time, in the RFC 3339 format, when the batch status became `canceled`. Present only when the status is `canceled`. */
    canceledAt?: Date;
    /** The date and time, in the RFC 3339 format, when the batch status became `expired`. Present only when the status is `expired`. */
    expiredAt?: Date;
}
