/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of video source.
 */
export type AnalyzeTaskWebhookVideoSourceType = "url" | "base64_string" | "asset_id" | "video_id";
export const AnalyzeTaskWebhookVideoSourceType = {
    Url: "url",
    Base64String: "base64_string",
    AssetId: "asset_id",
    VideoId: "video_id",
} as const;
