/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * The video source associated with an analysis task.
 */
export interface AnalyzeTaskWebhookVideoSource {
    /** The type of video source. */
    type: TwelvelabsApi.AnalyzeTaskWebhookVideoSourceType;
    /** The video URL. Present when `type` is `url`. */
    url?: string;
    /** The asset identifier. Present when `type` is `asset_id`. */
    assetId?: string;
    /** The video identifier. Present when `type` is `video_id`. */
    videoId?: string;
    /** Video metadata that the platform extracted during processing, such as its duration. Present on a best-effort basis when the duration is available. */
    systemMetadata?: TwelvelabsApi.AnalyzeTaskWebhookVideoSourceSystemMetadata;
}
