/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An image from the request, returned in the response. It can be a reference in the prompt or the analysis subject. For an image submitted through the `base64_string` field, the platform returns only `name` and `media_type`.
 */
export interface AnalyzeTaskMediaSource {
    /** The reference name you supplied. */
    name: string;
    /** The media type. The value is always `image`. */
    mediaType: string;
    /** Present when the source was provided as a URL. */
    url?: string;
    /** Present when the source was provided as an asset identifier. */
    assetId?: string;
}
