/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * The parameters you sent when creating this task. Only present for tasks created with `model_name` set to `pegasus1.5`.
 */
export interface AnalyzeTaskResponseRequestParams {
    /** The analysis approach for this task. */
    analysisMode?: TwelvelabsApi.AnalyzeTaskResponseRequestParamsAnalysisMode;
    /** The response format you configured. Present only when you included it in the request. */
    responseFormat?: TwelvelabsApi.AnalyzeTaskResponseRequestParamsResponseFormat;
    /** The temperature value for this analysis. */
    temperature?: number;
    /** The maximum number of tokens for the response. */
    maxTokens?: number;
    /** The minimum segment duration you set, in seconds. Present when `analysis_mode` is `time_based_metadata`. */
    minSegmentDuration?: number;
    /** The maximum segment duration you set, in seconds. Present when `analysis_mode` is `time_based_metadata`. */
    maxSegmentDuration?: number;
}
