/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * The video source you provided.
 */
export interface AnalyzeTaskResponseVideoSource {
    /** The type of video source. */
    type?: TwelvelabsApi.AnalyzeTaskResponseVideoSourceType;
    /** The video URL. Present when `type` is `url`. */
    url?: string;
    /** The asset ID. Present when `type` is `asset_id`. */
    assetId?: string;
    /** System-extracted video metadata. Present on a best-effort basis once the video has been processed. */
    systemMetadata?: TwelvelabsApi.AnalyzeTaskResponseVideoSourceSystemMetadata;
}
