/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The element type for an `array` field.
 */
export interface AnalyzeTaskTimeArrayItemFieldItems {
    /** The type of the array elements. */
    type: string;
}
