/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A time window within the video, expressed in seconds.
 */
export interface AnalyzeTimeRange {
    /** The start of the window, in seconds. Must be less than `end_time` and within the video duration. */
    startTime: number;
    /** The end of the window, in seconds. Must be greater than `start_time` by at least `2` seconds and within the video duration. */
    endTime: number;
}
