/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * The analysis results for a completed task.
 */
export interface AnalyzeTaskResult {
    /** The unique identifier for the generation session. */
    generationId: string;
    /**
     * The generated text for this analysis task. The format depends on the `analysis_mode` used when creating the task:
     *
     * - **When `analysis_mode` is not set**: A plain-text string containing the generated text based on the prompt you provided.
     * - **When `analysis_mode` is `time_based_metadata`**: A JSON-encoded string containing an object keyed by segment definition (the `id` field). Each key maps to an array of segment objects with the following fields:
     *   - `start_time` (number): The start time of the segment in seconds.
     *   - `end_time` (number): The end time of the segment in seconds.
     *   - `metadata` (object): The custom fields you defined in `segment_definitions[].fields`. The value of a `time_array` field is an array of event objects, one for each event inside the segment. Each event object contains `start_time` and `end_time`, which the platform adds automatically, plus the fields you declared in the `items.fields` array.
     *     - Segments are within the duration of the video, and events are within the duration of their segment.
     *     - The `min_segment_duration` and `max_segment_duration` values limit segments only, not the events inside them.
     *     - Event boundaries use the same format as segment boundaries, set by the `segment_time_format` value.
     */
    data: string;
    /**
     * When the task uses general analysis, `length` means the response reached the maximum response length or the context window. The partial output is in `data`, and a warning is in the task's `error` field.
     * With video segmentation and a numeric `max_tokens`, the task fails when the analysis reaches either limit. This field is never `length` for a segmentation task. With `max_tokens` set to `unlimited`, this field is `stop` even when the output is incomplete.
     */
    finishReason: TwelvelabsApi.FinishReason;
    /** The number of tokens used in the generation. */
    usage: TwelvelabsApi.AnalyzeTaskResultUsage;
}
