/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * Describes where an asset came from. The platform sets this field for assets imported through a connector; it is absent for assets uploaded directly to the `/assets` endpoint.
 */
export interface AssetSource {
    /** The kind of source. */
    type?: TwelvelabsApi.AssetSourceType;
    /** Provider-specific details about the origin of the file. The fields depend on the value of the `type` field. */
    details?: TwelvelabsApi.AssetSourceDetails;
}
