/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A timestamped transcription entry for a speaker turn.
 */
export interface AssetTranscriptionUtterance {
    /** The start timestamp in seconds. */
    start: number;
    /** The end timestamp in seconds. */
    end: number;
    /** The recognized text in this speaker turn. */
    value: string;
    /** The speaker identifier when available. */
    speaker?: string;
}
