/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * A reference file (image, audio, or video) that you upload to the platform for use in downstream workflows such as indexing, analyzing video content, and creating entities.
 */
export interface Asset {
    /** The unique identifier of the asset. */
    id?: string;
    /**
     * Indicates how you uploaded the asset.
     *
     * **Values**:
     * - `direct`: Uploaded from your local file system
     * - `url`: Uploaded from a publicly accessible URL
     */
    method?: TwelvelabsApi.AssetMethod;
    /**
     * Indicates the current status of the asset.
     *
     * **Values**:
     * - `failed`: The platform failed to process the upload
     * - `processing`: The platform is processing the uploaded file
     * - `ready`: The asset is ready to use
     */
    status?: TwelvelabsApi.AssetStatus;
    /** The name of the file used to create the asset. */
    filename?: string;
    /** The MIME type of the asset file. */
    fileType?: string;
    /** The date and time, in RFC 3339 format ("YYYY-MM-DDTHH:mm:ssZ"), when the asset was created. */
    createdAt?: Date;
}
