/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * This field is required if the `input_type` parameter is `image`. Requires Marengo 3.5. The image can be up to 32 MB before encoding, whether you provide a URL, an asset identifier, or base64-encoded data. For an image, the `embedding_option`, `embedding_type`, and `embedding_scope` fields each accept a single value; any other value returns a `400` error.
 */
export interface AsyncImageInputRequest {
    mediaSource: TwelvelabsApi.MediaSource;
    /** The type of embedding to generate for the image. Always `visual`. */
    embeddingOption?: TwelvelabsApi.AsyncImageInputRequestEmbeddingOptionItem[];
    /** Specifies how to structure the embedding. Always `separate_embedding`. */
    embeddingType?: TwelvelabsApi.AsyncImageInputRequestEmbeddingTypeItem[];
    /** The scope for which to generate embeddings. Always `asset`, which produces one embedding for the entire image. */
    embeddingScope?: TwelvelabsApi.AsyncImageInputRequestEmbeddingScopeItem[];
}
