/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AsyncAudioInputRequestEmbeddingTypeItem = "separate_embedding" | "fused_embedding";
export const AsyncAudioInputRequestEmbeddingTypeItem = {
    SeparateEmbedding: "separate_embedding",
    FusedEmbedding: "fused_embedding",
} as const;
