/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AsyncVideoInputRequestEmbeddingScopeItem = "clip" | "local" | "asset";
export const AsyncVideoInputRequestEmbeddingScopeItem = {
    Clip: "clip",
    Local: "local",
    Asset: "asset",
} as const;
