/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * Specifies how the platform divides the audio into segments.
 *
 * The structure of this object depends on the model version:
 *
 * - **With Marengo 3.5**: Place your settings in the `temporal` object. Both strategies are available: `dynamic` divides the audio into variable-length segments that follow scene changes, and `fixed` divides it into equal-length segments. Default: `temporal.dynamic`, `min_duration_sec: 2`.
 * - **With Marengo 3.0**: Provide the settings directly in this object. Only `fixed` segmentation is available. Default: `fixed`, `duration_sec: 6`.
 *
 * Using a structure that does not match your model version returns a `400` error.
 */
export type AsyncAudioInputRequestSegmentation =
    TwelvelabsApi.AudioSegmentation | TwelvelabsApi.AsyncTemporalSegmentation;
