/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * An object that contains the generated embedding vector and associated information.
 */
export interface AudioEmbeddingResult {
    /** An object that contains the embedding and its start time. */
    segments?: TwelvelabsApi.AudioSegment[];
    /** Error message if the embedding generation failed. */
    errorMessage?: string;
    metadata?: TwelvelabsApi.BaseEmbeddingMetadata;
}
