/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * An object containing metadata associated with the embedding.
 */
export interface AudioEmbeddingMetadata extends TwelvelabsApi.BaseEmbeddingMetadata {
    /** The type of the embedding. It can take one of the following values: ['audio'] or ['transcription']. */
    audioEmbeddingOptions?: string[];
    /** The scope you've specified in the request. */
    audioEmbeddingScopes?: string[];
    /** The total duration of the audio in seconds. */
    duration?: number;
    /** The start offset in seconds from the beginning of the audio where processing should begin. */
    startOffsetSec?: number;
    /** The end offset in seconds from the beginning of the audio where processing should end. */
    endOffsetSec?: number;
}
