/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * A single analysis request inside a batch. Identify the video in the `video` field. Every other field is optional and overrides the matching field in the `defaults` object.
 */
export interface BatchItemRequest {
    /** Identifies the asset to analyze. */
    video: TwelvelabsApi.BatchVideoContext;
    /**
     * An optional identifier you set per item when you create the batch. Use this field to map batch results back to records in your system, for example, to correlate each result with the source video in your database.
     *
     * The platform stores this value unchanged. It appears in:
     * - **Batch responses**: the array named `items` in the Create a batch response, and each line returned by the [`GET`](/v1.3/api-reference/analyze-videos/batch-analysis/retrieve-batch-results) method of the `/analyze/batches/{batch_id}/results` endpoint.
     * - **Task responses**: each batch request creates an analysis task. The `custom_id` field appears in the [`GET`](/v1.3/api-reference/analyze-videos/retrieve-analysis-task-status-results) method of the `/analyze/tasks/{task_id}` endpoint, the [`GET`](/v1.3/api-reference/analyze-videos/list-async-analysis-tasks) method of the `/analyze/tasks` endpoint, and the `analyze.task.ready` and `analyze.task.failed` webhook payloads.
     *
     * **Format**: 1–64 characters. Alphanumeric, hyphens (`-`), and underscores (`_`) only. An empty string is rejected with a `400 Bad Request`.
     *
     * The value must be unique within a batch. Submitting two items with the same value in the `custom_id` field in the same batch returns a `400 Bad Request`. Items without a custom identifier still receive a unique task identifier generated by the platform in results.
     */
    customId?: string;
    prompt?: TwelvelabsApi.BatchPrompt;
    responseFormat?: TwelvelabsApi.AsyncResponseFormat;
    temperature?: TwelvelabsApi.AnalyzeTemperature;
    /** Override the `defaults.max_tokens` value for this item. */
    maxTokens?: number;
    /** Override the `defaults.min_segment_duration` value for this item. */
    minSegmentDuration?: number;
    /** Override the `defaults.max_segment_duration` value for this item. */
    maxSegmentDuration?: number;
    /** Override the `defaults.start_time` value for this item. */
    startTime?: number;
    /** Override the `defaults.end_time` value for this item. */
    endTime?: number;
}
