/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Set this field to `asset_id` to indicate that you're providing the video as an asset.
 */
export type BatchVideoContextType = "asset_id";
export const BatchVideoContextType = {
    AssetId: "asset_id",
} as const;
