/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Failure details for a single batch item.
 */
export interface BatchItemError {
    /** A machine-readable error code identifying the failure category. */
    code?: string;
    /** A human-readable explanation of the failure. */
    message: string;
}
