/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * The task identifier and the `canceled` status.
 */
export interface CancelAnalyzeTaskResponse {
    /** The unique identifier of the analysis task. */
    taskId: string;
    /** The final status of the task. */
    status: TwelvelabsApi.CancelAnalyzeTaskResponseStatus;
}
