/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The current status of this chunk. This field can take one of the following values:
 * - `completed`: Successfully uploaded and reported.
 * - `pending`: Not yet reported. A chunk may be in this status if it has been uploaded but not yet reported.
 * - `failed`: The upload process failed; you must retry uploading this chunk.
 */
export type ChunkInfoStatus = "completed" | "pending" | "failed";
export const ChunkInfoStatus = {
    Completed: "completed",
    Pending: "pending",
    Failed: "failed",
} as const;
