/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The number of dimensions for each embedding in this response. Only Marengo 3.5 returns this field.
 */
export type EmbeddingDimension = number;
