/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EmbeddingVideoMetadataEmbeddingScopesItem = "clip" | "asset";
export const EmbeddingVideoMetadataEmbeddingScopesItem = {
    Clip: "clip",
    Asset: "asset",
} as const;
