/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * An embedding with its metadata.
 */
export interface EmbeddingData {
    /** The embedding vector for the content. */
    embedding: number[];
    /**
     * The modality used to generate this embedding.
     *
     *   **Values**:
     *  - `visual`: Embedding based on visual content (video only)
     *  - `audio`: Embedding based on audio content
     *  - `transcription`: Embedding based on transcribed speech
     *  - `fused`: Embedding based on a combination of the modalities specified in the request. The platform returns this embedding only for video and audio content, and only when the `embedding_type` parameter in the request includes `fused_embedding`.
     *  - `null`: For text and image embeddings
     */
    embeddingOption?: TwelvelabsApi.EmbeddingDataEmbeddingOption;
    /**
     * The scope for which the embedding was generated.
     *
     * **Values**:
     * - `clip`: Embedding for a segment
     * - `asset`: Embedding for the entire file. Use this scope for videos up to 10-30 seconds to maintain optimal performance.
     * - `null`: For text and image embeddings
     */
    embeddingScope?: TwelvelabsApi.EmbeddingDataEmbeddingScope;
    /** The start time in seconds for this segment. This field is `null` for text and image embeddings. */
    startSec?: number;
    /** The end time in seconds for this segment. This field is `null` for text and image embeddings. */
    endSec?: number;
}
