/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Token counts for the request. Only Marengo 3.5 returns this object.
 */
export interface EmbeddingUsage {
    /** The number of tokens the request used. Each key names a type of content the request processed, and each value is the token count for that content. */
    inputTokens: Record<string, number>;
    /** Whether the input was truncated to fit within the token limit. */
    truncated: boolean;
}
