/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * An object containing the status of the embedding task and the embeddings (when ready).
 */
export interface EmbeddingTaskResponse {
    /** The unique identifier of the embedding task. */
    id: string;
    /**
     * The current status of the task.
     * - `processing`: The platform is creating the embeddings
     * - `ready`: Processing is complete. Embeddings are available in the `data` field
     * - `failed`: The task failed. The `data` field is `null`
     */
    status: TwelvelabsApi.EmbeddingTaskResponseStatus;
    createdAt?: TwelvelabsApi.CreatedAt;
    updatedAt?: TwelvelabsApi.UpdatedAt;
    /** An array of embedding results. The platform retruns this field when `status` is `ready`. */
    data?: TwelvelabsApi.EmbeddingData[];
    metadata?: TwelvelabsApi.EmbeddingTaskMediaMetadata;
}
