/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * Metadata for audio embeddings
 */
export interface EmbeddingAudioMetadata {
    /** The publicly accessible URL for the audio file */
    inputUrl?: string;
    /** The name of the audio file */
    inputFilename?: string;
    /** Audio embedding options used for generating the embedding */
    embeddingOptions: string[];
    /** Audio embedding scopes */
    embeddingScopes: TwelvelabsApi.EmbeddingAudioMetadataEmbeddingScopesItem[];
    /** Duration of the audio in seconds */
    duration: number;
    /** Start offset in seconds */
    startOffsetSec?: number;
    /** End offset in seconds */
    endOffsetSec?: number;
}
