/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An object describing why the embedding task failed. Present only when `status` is `failed`. Omitted otherwise.
 */
export interface EmbeddingTaskResponseError {
    /**
     * A human-readable message that describes why the task failed. Possible values:
     * - "The embedding service is temporarily unstable. Please try again later."
     * - "The embedding task failed. Please try again later."
     * - "We could not process your media for embedding. Please verify the input file and try again." For the steps to fix the file, see the [How do I fix a file that could not be processed for embedding?](/v1.3/docs/resources/frequently-asked-questions#how-do-i-fix-a-file-that-could-not-be-processed-for-embedding) section on the **Frequently asked questions** page.
     */
    message: string;
}
