/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EmbeddingDataQuadrant = "top_left" | "top_right" | "bottom_left" | "bottom_right";
export const EmbeddingDataQuadrant = {
    TopLeft: "top_left",
    TopRight: "top_right",
    BottomLeft: "bottom_left",
    BottomRight: "bottom_right",
} as const;
