/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * Token counts for the request. Only Marengo 3.5 returns this object.
 */
export interface EmbeddingUsage {
    /**
     * The number of tokens the request used. Each key names a type of content the request processed, and each value is the token count for that content.
     *
     * The platform reports the content types your request actually used. Each key is one of the following: `video`, `audio`, `image`, `document`, or `text`. Read the keys the response returns rather than assuming a fixed set.
     */
    inputTokens: Record<string, number>;
    /** Whether the input was truncated to fit within the token limit. */
    truncated: boolean;
    /**
     * The reason the input was truncated. Present only when the `truncated` field is `true`.
     *
     * **Values**:
     * - `model_context_window`: The input exceeded the context window of the model.
     */
    truncationReason?: TwelvelabsApi.EmbeddingUsageTruncationReason;
}
