/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * A JSON Schema (draft 2020-12) that defines the structure of metadata to
 * extract from each video shot. The platform accepts only the JSON Schema keywords
 * listed below; unknown keywords return a `422` error. Keep schemas
 * focused — deeply nested or overly complex schemas may degrade extraction quality.
 *
 * **Supported keywords**
 *
 * | Category | Keywords |
 * |---|---|
 * | Core | `type`, `title`, `description`, `enum` |
 * | Object | `properties`, `required`, `additionalProperties` |
 * | Array | `items`, `prefixItems`, `minItems`, `maxItems` |
 * | Number | `minimum`, `maximum` |
 * | String | `format` |
 *
 * Notes:
 *
 * - The root `type` keyword must be `"object"`.
 * - Every entry under the `properties` keyword (including nested ones) must include a
 *   `description` field. This text guides extraction quality.
 * - The `required` keyword behaves as in standard JSON Schema.
 * - The `additionalProperties` keyword accepts a boolean value (`true` or `false`). Use
 *   `false` to enforce strict shapes. The platform does not support schema-valued forms.
 * - **Unknown keywords return `422` — they are not silently ignored.** If you
 *   generate schemas programmatically (for example, using
 *   `pydantic.model_json_schema()`), strip annotative keywords such as
 *   `default`, `examples`, and `readOnly` before submitting.
 * - **The platform does not support nullable fields.** This includes both `nullable: true` and
 *   `type: ["string", "null"]`. To express an optional field,
 *   omit it from the `required` array — the platform omits the field from the result
 *   when no value is present.
 *
 * **Not supported (returns `422`)**
 *
 * - Schema composition: `anyOf`, `allOf`, `oneOf`, `not`
 * - Conditional schemas: `if` / `then` / `else`
 * - Property dependencies: `dependentSchemas`, `dependentRequired`
 * - Object size constraints: `minProperties`, `maxProperties`
 * - String constraints: `pattern`, `minLength`, `maxLength`
 * - Number constraints: `exclusiveMinimum`, `exclusiveMaximum`, `multipleOf`
 * - Value constraints: `const`
 * - Null handling: `nullable`, `type` arrays (e.g., `["string", "null"]`)
 * - Annotative keywords: `default`, `examples`, `readOnly`, `writeOnly`
 * - References and reuse: `$ref`, `$defs`, `definitions`
 * - Any other keyword not listed under "Supported keywords" above
 */
export interface EnrichmentConfigJsonSchemaJsonSchema {
    /**
     * The top-level type of the schema. Must be `"object"`. Primitive and array
     * top-level types are not supported. The platform uses this object structure
     * to map extracted metadata to named fields.
     */
    type: TwelvelabsApi.EnrichmentConfigJsonSchemaJsonSchemaType;
    /**
     * A map of property names to their JSON Schema definitions. Each property
     * must include a field named `description`. The platform uses this field to guide extraction
     * quality. Omitting it returns a `422` error.
     */
    properties: Record<string, unknown>;
    /** Accepts any additional properties */
    [key: string]: any;
}
