/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The reason the generation stopped.
 * - `stop`: The generation reached the end of the output text.
 * - `length`: The generation reached the maximum response length or the context window. With a JSON response format, the output may be truncated and fail to parse.
 */
export type FinishReason = "stop" | "length";
export const FinishReason = {
    Stop: "stop",
    Length: "length",
} as const;
