/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The reason the generation stopped.
 * - `stop`: The generation reached the end of the output text.
 * - `length`: The response reached the maximum response length or the context window. For JSON responses, this may return truncated JSON that fails to parse.
 */
export type FinishReason = "stop" | "length";
export const FinishReason = {
    Stop: "stop",
    Length: "length",
} as const;
