/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GistRequestTypesItem = "title" | "topic" | "hashtag";
export const GistRequestTypesItem = {
    Title: "title",
    Topic: "topic",
    Hashtag: "hashtag",
} as const;
