/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * Metadata attached to an image knowledge store item in search results.
 */
export interface ImageSearchItemMetadata {
    /** System-generated media metadata for the source image. */
    system?: TwelvelabsApi.ImageSearchSystemMetadata;
    /** Caller-supplied key-value pairs attached to the item. */
    user?: TwelvelabsApi.UserMetadata;
}
