/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * An object containing metadata associated with the embedding. Only Marengo 3.5 returns this object.
 */
export interface ImageEmbeddingMetadata extends TwelvelabsApi.BaseEmbeddingMetadata {
    /** The `embedding_option` values used to generate the embedding. Always `["visual"]`. */
    imageEmbeddingOption?: string[];
    /** The `embedding_scope` values used to generate the embedding. Always `["asset"]`. */
    imageEmbeddingScope?: string[];
}
