/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * System-generated media metadata for an image item.
 */
export interface ImageMetadata {
    /** The original filename of the image. */
    filename?: string;
    /** The width of the image in pixels. */
    width?: number;
    /** The height of the image in pixels. */
    height?: number;
    /** The codec used to encode the image. */
    codecName?: string;
    /** The file size of the image in bytes. */
    size?: number;
}
