/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * An object that contains information about the import process.
 */
export interface ImportLog {
    /** The unique identifier of the index associated with this import. */
    indexId?: string;
    /** The name of the index associated with this import. */
    indexName?: string;
    /** The date and time, in the RFC 3339 format when the import process was initiated. */
    createdAt?: Date;
    /** The date and time, in the RFC 3339 format, when the platform completed importing your videos. A `null` value indicates that the import process is still ongoing. */
    endedAt?: Date;
    /** Counts of files in different statuses. See the [Task object](/v1.3/api-reference/upload-content/tasks/the-task-object) page for details on each status. */
    videoStatus?: TwelvelabsApi.ImportLogVideoStatus;
    /** An array containing the video files that failed to import, along with details about the error. */
    failedFiles?: TwelvelabsApi.ImportLogFailedFilesItem[];
}
