/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * A single import of files from a connected account. An import does not change after it is created.
 */
export interface Import {
    /** The unique identifier of the import. */
    id?: string;
    /** The unique identifier of the connection the files were imported through. */
    connectionId?: string;
    /** The data connector provider. */
    provider?: TwelvelabsApi.ImportProvider;
    /** The label you supplied when creating the connection, copied when the import was created. Present only when a value is set for the `custom_id` field. */
    customId?: string;
    /** The number of files requested in this import. If an imported asset is later deleted, it is omitted from the `items` array in the Retrieve an import response, so the `items` array can contain fewer entries than `item_count`. */
    itemCount?: number;
    /** The date and time, in the RFC 3339 format ("YYYY-MM-DDTHH:mm:ssZ"), when the import was created. */
    createdAt?: Date;
}
