/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the asset. See [The import object](/v1.3/api-reference/data-connectors/imports/the-import-object#item-statuses) for the possible values. Absent when the item was rejected before an asset was created, in which case an `error` object is present.
 */
export type ImportItemStatus = "processing" | "ready" | "failed";
export const ImportItemStatus = {
    Processing: "processing",
    Ready: "ready",
    Failed: "failed",
} as const;
