/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ImportLogFailedFilesItem {
    /** The name of the video file that failed to import. */
    filename?: string;
    /** A human-readable error message. */
    errorMessage?: string;
}
