/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IndexModelsItem {
    /** A string representing the name of the model. */
    modelName?: string;
    /** An array of strings that contains the [model options](/v1.3/docs/concepts/modalities#model-options) enabled for this index. */
    modelOptions?: string[];
}
