/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the indexing task.
 */
export type IndexedAssetStatus = "ready" | "pending" | "queued" | "indexing" | "failed";
export const IndexedAssetStatus = {
    Ready: "ready",
    Pending: "pending",
    Queued: "queued",
    Indexing: "indexing",
    Failed: "failed",
} as const;
