/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The index to which the indexed asset belongs.
 */
export interface IndexedAssetSummaryIndex {
    /** The unique identifier of the index. */
    id?: string;
    /** The name of the index. */
    name?: string;
}
