/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of item in the knowledge store.
 */
export type KnowledgeStoreItemAssetType = "video" | "image";
export const KnowledgeStoreItemAssetType = {
    Video: "video",
    Image: "image",
} as const;
