/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The processing status of the item. For the meaning of each value, see the
 * [Item statuses](/v1.3/api-reference/knowledge-store-items/the-knowledge-store-item-object#item-statuses)
 * section on **The knowledge store item object** page.
 */
export type KnowledgeStoreItemStatus = "queued" | "pending" | "processing" | "ready" | "failed";
export const KnowledgeStoreItemStatus = {
    Queued: "queued",
    Pending: "pending",
    Processing: "processing",
    Ready: "ready",
    Failed: "failed",
} as const;
