/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The search query.
 */
export interface KnowledgeStoreSearchQuery {
    /** Describe what you're searching for in natural language (Examples: `A person cooking pasta` or `aerial shots of a city at night`). */
    text: string;
}
