/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A named collection of items within a knowledge store. Use item collections to organize and reference subsets of items together. The items themselves are not affected.
 */
export interface KnowledgeStoreItemCollection {
    /** The unique identifier of the item collection. */
    id?: string;
    /** The unique identifier of the knowledge store this collection belongs to. */
    knowledgeStoreId?: string;
    /** The name of the item collection. */
    name?: string;
    /** The description of the item collection. */
    description?: string;
    /** Custom metadata for the item collection. */
    metadata?: Record<string, string>;
    /** The number of items in the collection. */
    memberCount?: number;
    /** The date and time when the item collection was created, in the RFC 3339 format. */
    createdAt?: Date;
    /** The date and time when the item collection was last updated, in the RFC 3339 format. */
    updatedAt?: Date;
}
