/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * A knowledge store contains your videos and images plus the understanding the platform derives from them: spatiotemporal context, a typed ontology, and embeddings for semantic retrieval. It is the corpus agents reason over: the full collection, not just individual clips.
 */
export interface KnowledgeStore {
    /** The unique identifier of the knowledge store. */
    id?: string;
    /** The name of the knowledge store. */
    name?: string;
    /** An optional description of the knowledge store. */
    description?: string;
    /** The ingestion configuration set when this knowledge store was created. Immutable. */
    ingestionConfig?: TwelvelabsApi.IngestionConfig;
    /** The number of items in the knowledge store. */
    itemCount?: number;
    /** The date and time when the knowledge store was created, in the RFC 3339 format. */
    createdAt?: Date;
    /** The date and time when the knowledge store was last updated, in the RFC 3339 format. */
    updatedAt?: Date;
    /** Custom metadata for the knowledge store. */
    metadata?: Record<string, string>;
}
