/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * An object containing the metadata associated with the embedding.
 */
export interface MediaEmbeddingTaskAudioEmbedding {
    metadata?: TwelvelabsApi.AudioEmbeddingMetadata;
}
