/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * When the value of the `stream` parameter is set to `false`, the response is as follows:
 */
export interface NonStreamAnalyzeResponse {
    /** Unique identifier of the response. */
    id?: string;
    data?: TwelvelabsApi.GeneratedTextData;
    finishReason?: TwelvelabsApi.FinishReason;
    usage?: TwelvelabsApi.TokenUsage;
    /** A warning. Present when `finish_reason` is `length` — the response reached the maximum response length or the [context window](/v1.3/docs/concepts/models/pegasus#context-window). The partial output is returned in `data`. Pegasus 1.2 also returns this field when `finish_reason` is `length`. */
    error?: TwelvelabsApi.AnalyzeTaskError;
}
