/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface NotFoundErrorBody {
    /** Represents the code associated with the error. See the [Error codes](/v1.3/api-reference/error-codes) page for details. */
    code?: string;
    /** A human-readable string describing the error. */
    message?: string;
}
