/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

export interface PresignedUrlChunk {
    /** The index of this chunk. */
    chunkIndex?: number;
    /** The presigned URL for uploading this chunk. Each URL can only be used once and expires after 1 hour. */
    url?: string;
    expiresAt?: TwelvelabsApi.ExpiresAt;
}
