/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An authorized redirect URI. During the authorization flow, the redirect URI you provide must match either a URI configured for you or one you registered through the [Register a redirect URI](/v1.3/api-reference/data-connectors/register-a-redirect-uri) method.
 */
export interface RedirectUri {
    /** The unique identifier of the redirect URI. */
    id?: string;
    /** The registered redirect URI. */
    redirectUri?: string;
    /** The date and time, in the RFC 3339 format ("YYYY-MM-DDTHH:mm:ssZ"), when the redirect URI was registered. */
    createdAt?: Date;
}
