/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

export interface RequestAdditionalPresignedUrLsResponse {
    /** The unique identifier of the upload session associated with these URLs. */
    uploadId?: string;
    /** The index of the first chunk number in this set of URLs. Matches the start value from your request. */
    startIndex?: number;
    /** The number of new URLs created. Matches the count value from your request. */
    count?: number;
    /** An array of additional presigned URLs for uploading chunks. */
    uploadUrls?: TwelvelabsApi.PresignedUrlChunk[];
    /** The date and time, in the RFC 3339 format ("YYYY-MM-DDTHH:mm:ssZ"), when these URLs were created. URLs remain valid for 1 hour from this time. */
    generatedAt?: Date;
    expiresAt?: TwelvelabsApi.ExpiresAt;
}
