/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * Emitted when a content part is finalized.
 */
export interface ResponseStreamContentPartDoneEvent extends TwelvelabsApi.ResponseStreamEventBase {
    /** The unique identifier of the parent output item. */
    itemId?: string;
    /** The index of the output item. */
    outputIndex?: number;
    /** The index of the content part. */
    contentIndex?: number;
    /**
     * The completed content part. The `annotations` array is populated.
     * Citations do not stream in with the text. You receive all of them on this
     * event, when the content part is complete.
     */
    part?: TwelvelabsApi.ResponseOutputContentPart;
}
