/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * Emitted when text streaming for a content part completes.
 */
export interface ResponseStreamOutputTextDoneEvent extends TwelvelabsApi.ResponseStreamEventBase {
    /** The unique identifier of the parent output item. */
    itemId?: string;
    /** The index of the output item. */
    outputIndex?: number;
    /** The index of the content part. */
    contentIndex?: number;
    /** The complete text content. */
    text?: string;
}
