/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Set this parameter to "json_schema" to receive structured JSON responses.
 */
export type ResponseFormatType = "json_schema";
export const ResponseFormatType = {
    JsonSchema: "json_schema",
} as const;
