/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The object type, always `response`. It has the same value as the `type`
 * field.
 *
 * Only the response itself has an `object` field. Output items, annotations,
 * and stream events are identified by `type` alone and have no `object` field.
 */
export type ResponseObjectObject = "response";
export const ResponseObjectObject = {
    Response: "response",
} as const;
