/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * An item in the response output. Items are polymorphic and discriminated by the `type` field.
 */
export interface ResponseOutputItem {
    /** The type of output item. */
    type: TwelvelabsApi.ResponseOutputItemType;
    /** A unique identifier for this item. */
    id: string;
    status: TwelvelabsApi.ResponseStatus;
    /** The role of the message author. Present when `type` is `message`. */
    role?: TwelvelabsApi.ResponseOutputItemRole;
    /**
     * Which part of the turn this message contains: intermediate output or the
     * answer. Present when the `type` field is `message`.
     *
     * A turn can produce intermediate messages before the answer, such as a
     * message that describes the steps Jockey is taking. The `commentary` value
     * identifies an intermediate message, and the `final_answer` value
     * identifies the answer.
     *
     * The output contains intermediate output only when the request sets the
     * `include` parameter to `["intermediate_outputs"]`. By default, the output
     * contains the answer only.
     *
     * Treat a message without the `phase` field as the final answer.
     *
     * Treat an unrecognized `phase` value as intermediate output, not as the
     * answer.
     */
    phase?: string;
    /** The content parts of the message. Present when `type` is `message`. */
    content?: TwelvelabsApi.ResponseOutputContentPart[];
    /** The name of the function. Present when `type` is `function_call`. */
    name?: string;
    /** The unique identifier for the function call. Present when `type` is `function_call`. */
    callId?: string;
    /** The JSON-encoded arguments for the function call. Present when `type` is `function_call`. */
    arguments?: string;
    /** The function call output. Present when `type` is `function_call_output`. */
    output?: string;
}
