/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of content part.
 */
export type ResponseOutputContentPartType = "output_text";
export const ResponseOutputContentPartType = {
    OutputText: "output_text",
} as const;
