/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * An item in the response output. Items are polymorphic and discriminated by the `type` field.
 */
export interface ResponseOutputItem {
    /** The type of output item. */
    type: TwelvelabsApi.ResponseOutputItemType;
    /** A unique identifier for this item. */
    id: string;
    status: TwelvelabsApi.ResponseStatus;
    /** The role of the message author. Present when `type` is `message`. */
    role?: TwelvelabsApi.ResponseOutputItemRole;
    /** The content parts of the message. Present when `type` is `message`. */
    content?: TwelvelabsApi.ResponseOutputContentPart[];
    /** The name of the function. Present when `type` is `function_call`. */
    name?: string;
    /** The unique identifier for the function call. Present when `type` is `function_call`. */
    callId?: string;
    /** The JSON-encoded arguments for the function call. Present when `type` is `function_call`. */
    arguments?: string;
    /** The function call output. Present when `type` is `function_call_output`. */
    output?: string;
}
