/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ResponseCreateRequestIncludeItem = "intermediate_outputs";
export const ResponseCreateRequestIncludeItem = {
    IntermediateOutputs: "intermediate_outputs",
} as const;
