/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * The search results. Each entry in the `data` array includes an `asset_type` field that indicates the type of item.
 */
export interface SearchKnowledgeStoreResponse {
    /** Search results, ordered by relevance. */
    data: TwelvelabsApi.SearchKnowledgeStoreHit[];
    /** Pagination token for the next page. Pass this value as the `page_token` parameter in your next request to retrieve more results. Absent when no more pages exist. */
    nextPageToken?: TwelvelabsApi.NextPageToken;
    /**
     * The video options applied to this search, including any defaults.
     *
     * - **When the search includes videos**: this object contains a `video` field with the modalities used.
     * - **When the search is limited to images** (the `filter.asset_type` field excludes videos): no video options apply, and this object is empty.
     *
     * Any option you omit is returned with its default value. For example, the `video` field shows `["visual"]` for modalities when you don't set `search_options.video`.
     */
    effectiveSearchOptions: TwelvelabsApi.SearchKnowledgeStoreOptions;
}
