/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * A single result in the search response. The fields present depend on the `asset_type` field.
 */
export type SearchKnowledgeStoreHit =
    TwelvelabsApi.SearchKnowledgeStoreHit.Video | TwelvelabsApi.SearchKnowledgeStoreHit.Image;

export namespace SearchKnowledgeStoreHit {
    export interface Video extends TwelvelabsApi.VideoSearchHit {
        assetType: "video";
    }

    export interface Image extends TwelvelabsApi.ImageSearchHit {
        assetType: "image";
    }
}
