/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * An object that contains the search results.
 */
export interface SearchItem {
    score?: TwelvelabsApi.ScoreSearchTerms;
    start?: TwelvelabsApi.StartTime;
    end?: TwelvelabsApi.EndTime;
    /** A string representing the unique identifier of the video. Once the platform indexes a video, it assigns a unique identifier. Note that this is different from the identifier of the video indexing task. */
    videoId?: string;
    confidence?: TwelvelabsApi.Confidence;
    rank?: TwelvelabsApi.Rank;
    thumbnailUrl?: TwelvelabsApi.ThumbnailUrl;
    /** A transcription of the spoken words that are captured in the video. */
    transcription?: string;
    /** A string representing the unique identifier of the video. It only appears when the `group_by=video` parameter is used in the request. */
    id?: string;
    userMetadata?: TwelvelabsApi.UserMetadata;
    /** An array that contains detailed information about the clips that match your query. The platform returns this array only when the `group_by` parameter is set to `video` in the request. */
    clips?: TwelvelabsApi.SearchItemClipsItem[];
}
