/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * An object that contains your search results.
 */
export interface SearchResults {
    /** An array that contains your search results. For each match found, the model returns the following fields: */
    data?: TwelvelabsApi.SearchItem[];
    /** An object that provides information about pagination. */
    pageInfo?: TwelvelabsApi.SearchResultsPageInfo;
    searchPool?: TwelvelabsApi.SearchPool;
}
