/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * Required when `type` is `array`. Specifies the type of array elements.
 */
export interface SegmentFieldItems {
    type: TwelvelabsApi.SegmentFieldItemsType;
}
