/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * An object that represents the response from a summarize chapter operation.
 */
export interface SummarizeChapterResult {
    /** Unique identifier of the response. */
    id?: string;
    /** An array that contains details about the detected chapters and their content. */
    chapters?: TwelvelabsApi.SummarizeChapterResultChaptersItem[];
    usage?: TwelvelabsApi.TokenUsage;
}
