/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of summarize response.
 */
export type SummarizeSummaryResultSummarizeType = "summary";
export const SummarizeSummaryResultSummarizeType = {
    Summary: "summary",
} as const;
