/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of summarize response.
 */
export type SummarizeChapterResultSummarizeType = "chapter";
export const SummarizeChapterResultSummarizeType = {
    Chapter: "chapter",
} as const;
