/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This field is required if `input_type` is `text`.
 */
export interface TextInputRequest {
    /** The text for which you wish to create an embedding. The maximul length is 500 tokens. */
    inputText: string;
}
