/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * An object containing the generated embedding vector.
 */
export interface TextEmbeddingResult {
    /** Error message if the embedding generation failed. */
    errorMessage?: string;
    /** An object that contains the embedding. */
    segments?: TwelvelabsApi.BaseSegment[];
}
