/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * If thumbnail generation has been enabled for this index, the platform returns a string representing the URL of the thumbnail. Note that the URL expires in one hour.
 */
export type ThumbnailUrl = string;
