/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Provide the video via a URL.
 */
export interface Url {
    /**
     * The publicly accessible URL of the video file.
     *
     * Use direct links to raw media files. Video hosting platforms and cloud storage sharing links are not supported.
     */
    url: string;
}
