/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

export interface VideoSegmentationDynamic {
    /** Configuration for dynamic segmentation. This object is required when `strategy` is `dynamic`. */
    dynamic: TwelvelabsApi.VideoSegmentationDynamicDynamic;
}
