/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The technical properties of a single video stream within the media file.
 */
export interface VideoStream {
    /** The zero-based index of the stream within the media file. */
    index?: number;
    /** The codec of the video stream. */
    codec?: string;
    /** The pixel width of the video stream. */
    width?: number;
    /** The pixel height of the video stream. */
    height?: number;
    /** The nominal frame rate of the video stream, in frames per second. */
    fps?: number;
    /** The average frame rate of the video stream, in frames per second. */
    avgFps?: number;
    /** The duration of the video stream, in seconds. */
    durationSeconds?: number;
    /** The bit rate of the video stream, in bits per second. */
    bitrateBps?: number;
    /** The rotation applied to the video stream, in degrees. */
    rotation?: number;
    /** The pixel (sample) aspect ratio of the video stream. */
    pixelAspectRatio?: string;
    /** The display aspect ratio of the video stream. */
    displayAspectRatio?: string;
    /** The scan type of the video stream (for example, progressive or interlaced). */
    scanType?: string;
    /** The pixel format of the video stream. */
    pixelFormat?: string;
    /** The bit depth per color component of the video stream. */
    bitDepth?: number;
    /** The color range of the video stream. */
    colorRange?: string;
    /** The color transfer characteristics of the video stream. */
    colorTransfer?: string;
    /** The color space of the video stream. */
    colorSpace?: string;
    /** The color primaries of the video stream. */
    colorPrimaries?: string;
}
