/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Configuration for dynamic segmentation. This object is required when `strategy` is `dynamic`.
 */
export interface VideoSegmentationDynamicDynamic {
    /**
     * The minimum duration in seconds for each segment.
     *
     * The platform divides the video into segments that are at least this long. Segments adapt to scene changes and content boundaries and may be longer than the minimum.
     *
     * **Example**: With `min_duration_sec: 3`, segments might be: [0-3.2s], [3.2-7.8s], [7.8-12.1s]
     */
    minDurationSec: number;
}
