/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../index";

/**
 * An object containing metadata associated with the embedding.
 */
export interface VideoEmbeddingMetadata extends TwelvelabsApi.BaseEmbeddingMetadata {
    /** The duration for each clip in seconds, as specified in the request. Note that the platform automatically truncates video segments shorter than 2 seconds. For a 31-second video divided into 6-second segments, the final 1-second segment will be truncated. This truncation only applies to the last segment if it does not meet the minimum length requirement of 2 seconds. */
    videoClipLength?: number;
    /** The scope you've specified in the request. */
    videoEmbeddingScope?: string[];
    /** The total duration of the video in seconds. */
    duration?: number;
}
