/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as TwelvelabsApi from "../../../../api/index";
import * as core from "../../../../core";

export const ResponsesCreateStreamRequestIncludeItem: core.serialization.Schema<
    serializers.ResponsesCreateStreamRequestIncludeItem.Raw,
    TwelvelabsApi.ResponsesCreateStreamRequestIncludeItem
> = core.serialization.enum_(["intermediate_outputs"]);

export declare namespace ResponsesCreateStreamRequestIncludeItem {
    export type Raw = "intermediate_outputs";
}
