/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import * as TwelvelabsApi from "../../../../../index";
import * as serializers from "../../../../../../serialization/index";
import { toJson } from "../../../../../../core/json";
import urlJoin from "url-join";
import * as errors from "../../../../../../errors/index";

export declare namespace IndexedAssets {
    export interface Options {
        environment?: core.Supplier<environments.TwelvelabsApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class IndexedAssets {
    constructor(protected readonly _options: IndexedAssets.Options = {}) {}

    /**
     * This method returns a list of the indexed assets in the specified index. By default, the platform returns your indexed assets sorted by creation date, with the newest at the top of the list.
     *
     * @param {string} indexId - The unique identifier of the index for which the platform will retrieve the indexed assets.
     * @param {TwelvelabsApi.indexes.IndexedAssetsListRequest} request
     * @param {IndexedAssets.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     *
     * @example
     *     await client.indexes.indexedAssets.list("6298d673f1090f1100476d4c", {
     *         page: 1,
     *         pageLimit: 10,
     *         sortBy: "created_at",
     *         sortOption: "desc",
     *         filename: "01.mp4",
     *         duration: 1.1,
     *         fps: 1.1,
     *         width: 1.1,
     *         height: 1,
     *         size: 1.1,
     *         createdAt: "2024-08-16T16:53:59Z",
     *         updatedAt: "2024-08-16T16:53:59Z"
     *     })
     */
    public async list(
        indexId: string,
        request: TwelvelabsApi.indexes.IndexedAssetsListRequest = {},
        requestOptions?: IndexedAssets.RequestOptions,
    ): Promise<core.Page<TwelvelabsApi.IndexedAsset>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TwelvelabsApi.indexes.IndexedAssetsListRequest,
            ): Promise<core.WithRawResponse<TwelvelabsApi.indexes.IndexedAssetsListResponse>> => {
                const {
                    page,
                    pageLimit,
                    sortBy,
                    sortOption,
                    status,
                    filename,
                    duration,
                    fps,
                    width,
                    height,
                    size,
                    createdAt,
                    updatedAt,
                    userMetadata,
                } = request;
                const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
                if (page != null) {
                    _queryParams["page"] = page.toString();
                }
                if (pageLimit != null) {
                    _queryParams["page_limit"] = pageLimit.toString();
                }
                if (sortBy != null) {
                    _queryParams["sort_by"] = sortBy;
                }
                if (sortOption != null) {
                    _queryParams["sort_option"] = sortOption;
                }
                if (status != null) {
                    if (Array.isArray(status)) {
                        _queryParams["status"] = status.map((item) =>
                            serializers.indexes.IndexedAssetsListRequestStatusItem.jsonOrThrow(item, {
                                unrecognizedObjectKeys: "strip",
                            }),
                        );
                    } else {
                        _queryParams["status"] = serializers.indexes.IndexedAssetsListRequestStatusItem.jsonOrThrow(
                            status,
                            { unrecognizedObjectKeys: "strip" },
                        );
                    }
                }
                if (filename != null) {
                    _queryParams["filename"] = filename;
                }
                if (duration != null) {
                    _queryParams["duration"] = duration.toString();
                }
                if (fps != null) {
                    _queryParams["fps"] = fps.toString();
                }
                if (width != null) {
                    _queryParams["width"] = width.toString();
                }
                if (height != null) {
                    _queryParams["height"] = height.toString();
                }
                if (size != null) {
                    _queryParams["size"] = size.toString();
                }
                if (createdAt != null) {
                    _queryParams["created_at"] = createdAt;
                }
                if (updatedAt != null) {
                    _queryParams["updated_at"] = updatedAt;
                }
                if (userMetadata != null) {
                    _queryParams["user_metadata"] = toJson(userMetadata);
                }
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.TwelvelabsApiEnvironment.Default,
                        `indexes/${encodeURIComponent(indexId)}/indexed-assets`,
                    ),
                    method: "GET",
                    headers: {
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "twelvelabs-js",
                        "X-Fern-SDK-Version": "1.1.0",
                        "User-Agent": "twelvelabs-js/1.1.0",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...(await this._getCustomAuthorizationHeaders()),
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    queryParameters: _queryParams,
                    requestType: "json",
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        data: serializers.indexes.IndexedAssetsListResponse.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                        default:
                            throw new errors.TwelvelabsApiError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.TwelvelabsApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                            rawResponse: _response.rawResponse,
                        });
                    case "timeout":
                        throw new errors.TwelvelabsApiTimeoutError(
                            "Timeout exceeded when calling GET /indexes/{index-id}/indexed-assets.",
                        );
                    case "unknown":
                        throw new errors.TwelvelabsApiError({
                            message: _response.error.errorMessage,
                            rawResponse: _response.rawResponse,
                        });
                }
            },
        );
        let _offset = request?.page != null ? request?.page : 1;
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Pageable<TwelvelabsApi.indexes.IndexedAssetsListResponse, TwelvelabsApi.IndexedAsset>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) => (response?.data ?? []).length > 0,
            getItems: (response) => response?.data ?? [],
            loadPage: (_response) => {
                _offset += 1;
                return list(core.setObjectProperty(request, "page", _offset));
            },
        });
    }

    /**
     * This method indexes an uploaded asset to make it searchable and analyzable. Indexing processes your content and extracts information that enables the platform to search and analyze your videos.
     *
     * This operation is asynchronous. The platform returns an indexed asset ID immediately and processes your content in the background. Monitor the indexing status to know when your content is ready to use.
     *
     * Your asset must meet the requirements based on your workflow:
     * - **Search**: [Marengo requirements](/v1.3/docs/concepts/models/marengo#video-file-requirements)
     * - **Video analysis**: [Pegasus requirements](/v1.3/docs/concepts/models/pegasus#input-requirements).
     *
     * If you want to both search and analyze your videos, the most restrictive requirements apply.
     *
     * @param {string} indexId - The unique identifier of the index to which the asset will be indexed.
     * @param {TwelvelabsApi.indexes.IndexedAssetsCreateRequest} request
     * @param {IndexedAssets.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     * @throws {@link TwelvelabsApi.NotFoundError}
     * @throws {@link TwelvelabsApi.InternalServerError}
     *
     * @example
     *     await client.indexes.indexedAssets.create("6298d673f1090f1100476d4c", {
     *         assetId: "6298d673f1090f1100476d4c"
     *     })
     */
    public create(
        indexId: string,
        request: TwelvelabsApi.indexes.IndexedAssetsCreateRequest,
        requestOptions?: IndexedAssets.RequestOptions,
    ): core.HttpResponsePromise<TwelvelabsApi.indexes.IndexedAssetsCreateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(indexId, request, requestOptions));
    }

    private async __create(
        indexId: string,
        request: TwelvelabsApi.indexes.IndexedAssetsCreateRequest,
        requestOptions?: IndexedAssets.RequestOptions,
    ): Promise<core.WithRawResponse<TwelvelabsApi.indexes.IndexedAssetsCreateResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                `indexes/${encodeURIComponent(indexId)}/indexed-assets`,
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.1.0",
                "User-Agent": "twelvelabs-js/1.1.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.indexes.IndexedAssetsCreateRequest.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.indexes.IndexedAssetsCreateResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new TwelvelabsApi.NotFoundError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new TwelvelabsApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError(
                    "Timeout exceeded when calling POST /indexes/{index-id}/indexed-assets.",
                );
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * This method retrieves information about an indexed asset, including its status, metadata, and optional embeddings or transcription.
     *
     * **Common use cases**:
     *
     * - Monitor indexing progress:
     *   - Call this endpoint after creating an indexed asset
     *   - Check the `status` field until it shows `ready`
     *   - Once ready, your content is available for search and analysis
     *
     * - Retrieve  asset metadata:
     *   - Retrieve system metadata (duration, resolution, filename)
     *   - Access user-defined metadata
     *
     * - Retrieve embeddings:
     *   - Include the `embedding_option` parameter to retrieve video embeddings
     *   - Requires the Marengo video understanding model to be enabled in your index
     *
     * - Retrieve transcriptions:
     *   - Set the `transcription` parameter to `true` to retrieve spoken words from your video
     *
     * @param {string} indexId - The unique identifier of the index to which the indexed asset has been uploaded.
     * @param {string} indexedAssetId - The unique identifier of the indexed asset to retrieve.
     * @param {TwelvelabsApi.indexes.IndexedAssetsRetrieveRequest} request
     * @param {IndexedAssets.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     * @throws {@link TwelvelabsApi.NotFoundError}
     *
     * @example
     *     await client.indexes.indexedAssets.retrieve("6298d673f1090f1100476d4c", "6298d673f1090f1100476d4c", {
     *         transcription: true
     *     })
     */
    public retrieve(
        indexId: string,
        indexedAssetId: string,
        request: TwelvelabsApi.indexes.IndexedAssetsRetrieveRequest = {},
        requestOptions?: IndexedAssets.RequestOptions,
    ): core.HttpResponsePromise<TwelvelabsApi.IndexedAssetDetailed> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(indexId, indexedAssetId, request, requestOptions));
    }

    private async __retrieve(
        indexId: string,
        indexedAssetId: string,
        request: TwelvelabsApi.indexes.IndexedAssetsRetrieveRequest = {},
        requestOptions?: IndexedAssets.RequestOptions,
    ): Promise<core.WithRawResponse<TwelvelabsApi.IndexedAssetDetailed>> {
        const { embeddingOption, transcription } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (embeddingOption != null) {
            if (Array.isArray(embeddingOption)) {
                _queryParams["embedding_option"] = embeddingOption.map((item) =>
                    serializers.indexes.IndexedAssetsRetrieveRequestEmbeddingOptionItem.jsonOrThrow(item, {
                        unrecognizedObjectKeys: "strip",
                    }),
                );
            } else {
                _queryParams["embedding_option"] =
                    serializers.indexes.IndexedAssetsRetrieveRequestEmbeddingOptionItem.jsonOrThrow(embeddingOption, {
                        unrecognizedObjectKeys: "strip",
                    });
            }
        }

        if (transcription != null) {
            _queryParams["transcription"] = transcription.toString();
        }

        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                `indexes/${encodeURIComponent(indexId)}/indexed-assets/${encodeURIComponent(indexedAssetId)}`,
            ),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.1.0",
                "User-Agent": "twelvelabs-js/1.1.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.IndexedAssetDetailed.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 404:
                    throw new TwelvelabsApi.NotFoundError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError(
                    "Timeout exceeded when calling GET /indexes/{index-id}/indexed-assets/{indexed-asset-id}.",
                );
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * This method deletes all the information about the specified indexed asset. This action cannot be undone.
     *
     * @param {string} indexId - The unique identifier of the index to which the indexed asset has been uploaded.
     * @param {string} indexedAssetId - The unique identifier of the indexed asset to delete.
     * @param {IndexedAssets.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     *
     * @example
     *     await client.indexes.indexedAssets.delete("6298d673f1090f1100476d4c", "6298d673f1090f1100476d4c")
     */
    public delete(
        indexId: string,
        indexedAssetId: string,
        requestOptions?: IndexedAssets.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(indexId, indexedAssetId, requestOptions));
    }

    private async __delete(
        indexId: string,
        indexedAssetId: string,
        requestOptions?: IndexedAssets.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                `indexes/${encodeURIComponent(indexId)}/indexed-assets/${encodeURIComponent(indexedAssetId)}`,
            ),
            method: "DELETE",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.1.0",
                "User-Agent": "twelvelabs-js/1.1.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError(
                    "Timeout exceeded when calling DELETE /indexes/{index-id}/indexed-assets/{indexed-asset-id}.",
                );
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Use this method to update one or more fields of the metadata of an indexed asset. Also, can delete a field by setting it to null.
     *
     * @param {string} indexId - The unique identifier of the index to which the indexed asset has been uploaded.
     * @param {string} indexedAssetId - The unique identifier of the indexed asset to update.
     * @param {TwelvelabsApi.indexes.IndexedAssetsUpdateRequest} request
     * @param {IndexedAssets.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     *
     * @example
     *     await client.indexes.indexedAssets.update("6298d673f1090f1100476d4c", "6298d673f1090f1100476d4c", {
     *         userMetadata: {
     *             "category": "recentlyAdded",
     *             "batchNumber": 5,
     *             "rating": 9.3,
     *             "needsReview": true
     *         }
     *     })
     */
    public update(
        indexId: string,
        indexedAssetId: string,
        request: TwelvelabsApi.indexes.IndexedAssetsUpdateRequest = {},
        requestOptions?: IndexedAssets.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__update(indexId, indexedAssetId, request, requestOptions));
    }

    private async __update(
        indexId: string,
        indexedAssetId: string,
        request: TwelvelabsApi.indexes.IndexedAssetsUpdateRequest = {},
        requestOptions?: IndexedAssets.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                `indexes/${encodeURIComponent(indexId)}/indexed-assets/${encodeURIComponent(indexedAssetId)}`,
            ),
            method: "PATCH",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.1.0",
                "User-Agent": "twelvelabs-js/1.1.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.indexes.IndexedAssetsUpdateRequest.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError(
                    "Timeout exceeded when calling PATCH /indexes/{index-id}/indexed-assets/{indexed-asset-id}.",
                );
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
