/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../../../environments";
import * as core from "../../../../../../../../core";
import * as TwelvelabsApi from "../../../../../../../index";
import urlJoin from "url-join";
import * as serializers from "../../../../../../../../serialization/index";
import * as errors from "../../../../../../../../errors/index";

export declare namespace Tasks {
    export interface Options {
        environment?: core.Supplier<environments.TwelvelabsApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Tasks {
    constructor(protected readonly _options: Tasks.Options) {}

    /**
     * This method returns a list of the async embedding tasks in your account. The platform returns your async embedding tasks sorted by creation date, with the newest at the top of the list.
     *
     * @param {TwelvelabsApi.embed.v2.TasksListRequest} request
     * @param {Tasks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     *
     * @example
     *     await client.embed.v2.tasks.list({
     *         startedAt: "2024-03-01T00:00:00Z",
     *         endedAt: "2024-03-01T00:00:00Z",
     *         status: "processing",
     *         page: 1,
     *         pageLimit: 10
     *     })
     */
    public async list(
        request: TwelvelabsApi.embed.v2.TasksListRequest = {},
        requestOptions?: Tasks.RequestOptions,
    ): Promise<core.Page<TwelvelabsApi.MediaEmbeddingTask>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TwelvelabsApi.embed.v2.TasksListRequest,
            ): Promise<core.WithRawResponse<TwelvelabsApi.embed.v2.TasksListResponse>> => {
                const { startedAt, endedAt, status, page, pageLimit } = request;
                const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
                if (startedAt != null) {
                    _queryParams["started_at"] = startedAt;
                }
                if (endedAt != null) {
                    _queryParams["ended_at"] = endedAt;
                }
                if (status != null) {
                    _queryParams["status"] = status;
                }
                if (page != null) {
                    _queryParams["page"] = page.toString();
                }
                if (pageLimit != null) {
                    _queryParams["page_limit"] = pageLimit.toString();
                }
                const _response = await core.fetcher({
                    url: urlJoin(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.TwelvelabsApiEnvironment.Default,
                        "embed-v2/tasks",
                    ),
                    method: "GET",
                    headers: {
                        "X-Fern-Language": "JavaScript",
                        "X-Fern-SDK-Name": "twelvelabs-js",
                        "X-Fern-SDK-Version": "1.2.0-beta.1",
                        "User-Agent": "twelvelabs-js/1.2.0-beta.1",
                        "X-Fern-Runtime": core.RUNTIME.type,
                        "X-Fern-Runtime-Version": core.RUNTIME.version,
                        ...(await this._getCustomAuthorizationHeaders()),
                        ...requestOptions?.headers,
                    },
                    contentType: "application/json",
                    queryParameters: _queryParams,
                    requestType: "json",
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        data: serializers.embed.v2.TasksListResponse.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                        default:
                            throw new errors.TwelvelabsApiError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.TwelvelabsApiError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                            rawResponse: _response.rawResponse,
                        });
                    case "timeout":
                        throw new errors.TwelvelabsApiTimeoutError(
                            "Timeout exceeded when calling GET /embed-v2/tasks.",
                        );
                    case "unknown":
                        throw new errors.TwelvelabsApiError({
                            message: _response.error.errorMessage,
                            rawResponse: _response.rawResponse,
                        });
                }
            },
        );
        let _offset = request?.page != null ? request?.page : 1;
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Pageable<TwelvelabsApi.embed.v2.TasksListResponse, TwelvelabsApi.MediaEmbeddingTask>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) => (response?.data ?? []).length > 0,
            getItems: (response) => response?.data ?? [],
            loadPage: (_response) => {
                _offset += 1;
                return list(core.setObjectProperty(request, "page", _offset));
            },
        });
    }

    /**
     * This endpoint creates embeddings for audio and video content asynchronously.
     *
     * <Note title="Note">
     *   This method only supports Marengo version 3.0 or newer.
     * </Note>
     *
     * **When to use this endpoint**:
     * - Process audio or video files longer than 10 minutes
     * - Process files up to 4 hours in duration
     *
     * <Accordion title="Input requirements">
     *   **Video**:
     *   - Minimum duration: 4 seconds
     *   - Maximum duration: 4 hours
     *   - Maximum file size: 4 GB
     *   - Formats: [FFmpeg supported formats](https://ffmpeg.org/ffmpeg-formats.html)
     *   - Resolution: 360x360 to 5184x2160 pixels
     *   - Aspect ratio: Between 1:1 and 1:2.4, or between 2.4:1 and 1:1
     *
     *   **Audio**:
     *   - Minimum duration: 4 seconds
     *   - Maximum duration: 4 hours
     *   - Maximum file size: 2 GB
     *   - Formats: WAV (uncompressed), MP3 (lossy), FLAC (lossless)
     * </Accordion>
     *
     *   Creating embeddings asynchronously requires three steps:
     *
     *   1. Create a task using this endpoint. The platform returns a task ID.
     *   2. Poll for the status of the task using the [`GET`](/v1.3/api-reference/create-embeddings-v2/retrieve-embeddings) method of the `/embed-v2/tasks/{task_id}` endpoint. Wait until the status is `ready`.
     *   3. Retrieve the embeddings from the response when the status is `ready` using the [`GET`](/v1.3/api-reference/create-embeddings-v2/retrieve-embeddings) method of the `/embed-v2/tasks/{task_id}` endpoint.
     *
     * @param {TwelvelabsApi.embed.v2.CreateAsyncEmbeddingRequest} request
     * @param {Tasks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.BadRequestError}
     * @throws {@link TwelvelabsApi.InternalServerError}
     *
     * @example
     *     await client.embed.v2.tasks.create({
     *         inputType: "audio",
     *         modelName: "marengo3.0",
     *         audio: {
     *             mediaSource: {
     *                 url: "https://user-bucket.com/audio/long-audio.wav"
     *             },
     *             startSec: 0,
     *             endSec: 3600,
     *             segmentation: {
     *                 strategy: "fixed",
     *                 fixed: {
     *                     durationSec: 6
     *                 }
     *             },
     *             embeddingOption: ["audio", "transcription"],
     *             embeddingScope: ["clip", "asset"]
     *         }
     *     })
     *
     * @example
     *     await client.embed.v2.tasks.create({
     *         inputType: "video",
     *         modelName: "marengo3.0",
     *         video: {
     *             mediaSource: {
     *                 url: "https://user-bucket.com/video/long-video.mp4"
     *             },
     *             startSec: 0,
     *             endSec: 7200,
     *             segmentation: {
     *                 strategy: "dynamic",
     *                 dynamic: {
     *                     minDurationSec: 4
     *                 }
     *             },
     *             embeddingOption: ["visual", "audio", "transcription"],
     *             embeddingScope: ["clip", "asset"]
     *         }
     *     })
     */
    public create(
        request: TwelvelabsApi.embed.v2.CreateAsyncEmbeddingRequest,
        requestOptions?: Tasks.RequestOptions,
    ): core.HttpResponsePromise<TwelvelabsApi.embed.v2.TasksCreateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: TwelvelabsApi.embed.v2.CreateAsyncEmbeddingRequest,
        requestOptions?: Tasks.RequestOptions,
    ): Promise<core.WithRawResponse<TwelvelabsApi.embed.v2.TasksCreateResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                "embed-v2/tasks",
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.2.0-beta.1",
                "User-Agent": "twelvelabs-js/1.2.0-beta.1",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: serializers.embed.v2.CreateAsyncEmbeddingRequest.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.embed.v2.TasksCreateResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TwelvelabsApi.BadRequestError(_response.error.body, _response.rawResponse);
                case 500:
                    throw new TwelvelabsApi.InternalServerError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError("Timeout exceeded when calling POST /embed-v2/tasks.");
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * This method retrieves the status and the results of an async embedding task.
     *
     * **Task statuses**:
     * - `processing`: The platform is creating the embeddings.
     * - `ready`: Processing is complete. Embeddings are available in the response.
     * - `failed`: The task failed. Embeddings were not created.
     *
     * Invoke this method repeatedly until the `status` field is `ready`. When `status` is `ready`, use the embeddings from the response.
     *
     * @param {string} taskId - The unique identifier of the embedding task.
     * @param {Tasks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TwelvelabsApi.NotFoundError}
     *
     * @example
     *     await client.embed.v2.tasks.retrieve("64f8d2c7e4a1b37f8a9c5d12")
     */
    public retrieve(
        taskId: string,
        requestOptions?: Tasks.RequestOptions,
    ): core.HttpResponsePromise<TwelvelabsApi.EmbeddingTaskResponse> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(taskId, requestOptions));
    }

    private async __retrieve(
        taskId: string,
        requestOptions?: Tasks.RequestOptions,
    ): Promise<core.WithRawResponse<TwelvelabsApi.EmbeddingTaskResponse>> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.TwelvelabsApiEnvironment.Default,
                `embed-v2/tasks/${encodeURIComponent(taskId)}`,
            ),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "twelvelabs-js",
                "X-Fern-SDK-Version": "1.2.0-beta.1",
                "User-Agent": "twelvelabs-js/1.2.0-beta.1",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.EmbeddingTaskResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new TwelvelabsApi.NotFoundError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.TwelvelabsApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.TwelvelabsApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.TwelvelabsApiTimeoutError(
                    "Timeout exceeded when calling GET /embed-v2/tasks/{task_id}.",
                );
            case "unknown":
                throw new errors.TwelvelabsApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
