/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as TwelvelabsApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const KnowledgeStoreItemCollectionsUpdateRequest: core.serialization.Schema<
    serializers.KnowledgeStoreItemCollectionsUpdateRequest.Raw,
    TwelvelabsApi.KnowledgeStoreItemCollectionsUpdateRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
});

export declare namespace KnowledgeStoreItemCollectionsUpdateRequest {
    export interface Raw {
        name?: string | null;
        description?: string | null;
        metadata?: Record<string, string> | null;
    }
}
