/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "Q1 highlights"
 *     }
 */
export interface KnowledgeStoreItemCollectionsCreateRequest {
    /** The name of the item collection. Must be unique within the knowledge store. */
    name: string;
    /** An optional description of the item collection. */
    description?: string;
    /** Custom metadata for the item collection. Both keys and values must be strings. */
    metadata?: Record<string, string>;
}
