/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface KnowledgeStoreItemCollectionsUpdateRequest {
    /** The name of the item collection. Must be unique within the knowledge store. */
    name?: string;
    /** An optional description of the item collection. */
    description?: string;
    /** Custom metadata for the item collection. Both keys and values must be strings. To remove all metadata, set this field to an empty object (`{}`). */
    metadata?: Record<string, string>;
}
