/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         indexName: "myIndex"
 *     }
 */
export interface IndexesUpdateRequest {
    /** The name of the index. */
    indexName: string;
}
