/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../index";

/**
 * @example
 *     {
 *         videoId: "6298d673f1090f1100476d4c",
 *         prompt: "I want to generate a description for my video with the following format - Title of the video, followed by a summary in 2-3 sentences, highlighting the main topic, key events, and concluding remarks.",
 *         temperature: 0.2,
 *         responseFormat: {
 *             type: "json_schema",
 *             jsonSchema: {
 *                 "type": "object",
 *                 "properties": {
 *                     "title": {
 *                         "type": "string"
 *                     },
 *                     "summary": {
 *                         "type": "string"
 *                     },
 *                     "keywords": {
 *                         "type": "array",
 *                         "items": {
 *                             "type": "string"
 *                         }
 *                     }
 *                 }
 *             }
 *         },
 *         maxTokens: 2000
 *     }
 */
export interface AnalyzeRequest {
    /**
     * The unique identifier of the video to analyze.
     *
     * <Info> This parameter will be deprecated and removed in a future version. Use the [`video`](/v1.3/api-reference/analyze-videos/sync-analysis#request.body.video) parameter instead.</Info>
     */
    videoId?: string;
    video?: TwelvelabsApi.VideoContext;
    prompt: TwelvelabsApi.AnalyzeTextPrompt;
    temperature?: TwelvelabsApi.AnalyzeTemperature;
    responseFormat?: TwelvelabsApi.ResponseFormat;
    maxTokens?: TwelvelabsApi.AnalyzeMaxTokens;
}
