/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         videoId: "6298d673f1090f1100476d4c",
 *         prompt: "I want to generate a description for my video with the following format - Title of the video, followed by a summary in 2-3 sentences, highlighting the main topic, key events, and concluding remarks.",
 *         temperature: 0.2,
 *         stream: true
 *     }
 *
 * @example
 *     {
 *         videoId: "6298d673f1090f1100476d4c",
 *         prompt: "I want to generate a description for my video with the following format - Title of the video, followed by a summary in 2-3 sentences, highlighting the main topic, key events, and concluding remarks.",
 *         temperature: 0.2,
 *         stream: true
 *     }
 *
 * @example
 *     {
 *         videoId: "6298d673f1090f1100476d4c",
 *         prompt: "I want to generate a description for my video with the following format - Title of the video, followed by a summary in 2-3 sentences, highlighting the main topic, key events, and concluding remarks.",
 *         temperature: 0.2,
 *         stream: true
 *     }
 *
 * @example
 *     {
 *         videoId: "6298d673f1090f1100476d4c",
 *         prompt: "I want to generate a description for my video with the following format - Title of the video, followed by a summary in 2-3 sentences, highlighting the main topic, key events, and concluding remarks.",
 *         temperature: 0.2,
 *         stream: true
 *     }
 */
export interface GenerateRequest {
    /** The unique identifier of the video for which you wish to generate a text. */
    videoId: string;
    /**
     * A prompt that guides the model on the desired format or content.
     *
     * <Note title="Notes">
     * - Even though the model behind this endpoint is trained to a high degree of accuracy, the preciseness of the generated text may vary based on the nature and quality of the video and the clarity of the prompt.
     * - Your prompts can be instructive or descriptive, or you can also phrase them as questions.
     * - The maximum length of a prompt is 2,000 tokens.
     * </Note>
     *
     * **Examples**:
     *
     * - Based on this video, I want to generate five keywords for SEO (Search Engine Optimization).
     * - I want to generate a description for my video with the following format: Title of the video, followed by a summary in 2-3 sentences, highlighting the main topic, key events, and concluding remarks.
     */
    prompt: string;
    /**
     * Controls the randomness of the text output generated by the model. A higher value generates more creative text, while a lower value produces more deterministic text output.
     *
     * **Default:** 0.2
     * **Min:** 0
     * **Max:** 1
     */
    temperature?: number;
    /**
     * Set this parameter to `true` to enable streaming responses in the <a href="https://github.com/ndjson/ndjson-spec" target="_blank">NDJSON</a> format.
     *
     * **Default:** `true`
     */
    stream?: boolean;
}
