/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TasksCreateResponse {
    /** A string representing the unique identifier of your video indexing task. */
    id?: string;
    /** A string representing the unique identifier of the video associated with the specified video indexing task. */
    videoId?: string;
}
