/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../index";

export interface TasksListResponse {
    /** An array that contains up to `page_limit` tasks. */
    data?: TwelvelabsApi.VideoIndexingTask[];
    /** An object that provides information about pagination. */
    pageInfo?: TwelvelabsApi.TasksListResponsePageInfo;
}
