/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as fs from "fs";
import * as TwelvelabsApi from "../../../../../../index";

/**
 * @example
 *     {
 *         modelName: "model_name"
 *     }
 */
export interface TasksCreateRequest {
    /**
     * The name of the model you want to use. The following models are available:
     *   - `Marengo-retrieval-2.7`
     */
    modelName: string;
    videoFile?: File | fs.ReadStream | Blob | undefined;
    /** Specify this parameter to upload a video from a publicly accessible URL. */
    videoUrl?: string;
    /**
     * The start offset in seconds from the beginning of the video where processing should begin. Specifying 0 means starting from the beginning of the video.
     *
     * **Default**: 0
     * **Min**: 0
     * **Max**: Duration of the video minus video_clip_length
     */
    videoStartOffsetSec?: number;
    /**
     * The end offset in seconds from the beginning of the video where processing should stop.
     *
     * Ensure the following when you specify this parameter:
     * - The end offset does not exceed the total duration of the video file.
     * - The end offset is greater than the start offset.
     * - You must set both the start and end offsets. Setting only one of these offsets is not permitted, resulting in an error.
     *
     * **Min**: video_start_offset + video_clip_length
     * **Max**: Duration of the video file
     */
    videoEndOffsetSec?: number;
    /**
     * The desired duration in seconds for each clip for which the platform generates an embedding. Ensure that the clip length does not exceed the interval between the start and end offsets.
     *
     * **Default**: 6
     * **Min**: 2
     * **Max**: 10
     */
    videoClipLength?: number;
    /**
     * Defines the scope of video embedding generation. Valid values are the following:
     * - `clip`: Creates embeddings for each video segment of `video_clip_length` seconds, from `video_start_offset_sec` to `video_end_offset_sec`.
     * - `clip` and `video`: Creates embeddings for video segments and the entire video.
     *
     * To create embeddings for segments and the entire video in the same request, include this parameter twice as shown below:
     *
     * ```json
     * --form video_embedding_scope=clip \
     * --form video_embedding_scope=video
     * ```
     *
     * **Default**: `clip`
     */
    videoEmbeddingScope?: TwelvelabsApi.embed.TasksCreateRequestVideoEmbeddingScopeItem[];
}
