/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         startedAt: "2024-03-01T00:00:00Z",
 *         endedAt: "2024-03-01T00:00:00Z",
 *         status: "processing",
 *         page: 1,
 *         pageLimit: 10
 *     }
 */
export interface TasksListRequest {
    /**
     * Retrieve the video embedding tasks that were created after the given date and time, expressed in the RFC 3339 format ("YYYY-MM-DDTHH:mm:ssZ").
     */
    startedAt?: string;
    /**
     * Retrieve the video embedding tasks that were created before the given date and time, expressed in the RFC 3339 format ("YYYY-MM-DDTHH:mm:ssZ").
     */
    endedAt?: string;
    /**
     * Filter video embedding tasks by their current status. Possible values are `processing`, `ready`, or `failed`.
     */
    status?: string;
    /**
     * A number that identifies the page to retrieve.
     *
     * **Default**: `1`.
     */
    page?: number;
    /**
     * The number of items to return on each page.
     *
     * **Default**: `10`.
     * **Max**: `50`.
     */
    pageLimit?: number;
}
