/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const AnalyzeTaskFailedWebhookEventType: core.serialization.Schema<
    serializers.AnalyzeTaskFailedWebhookEventType.Raw,
    TwelvelabsApi.AnalyzeTaskFailedWebhookEventType
> = core.serialization.enum_(["analyze.task.failed"]);

export declare namespace AnalyzeTaskFailedWebhookEventType {
    export type Raw = "analyze.task.failed";
}
