/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { AnalyzeTaskReadyWebhookDataStatus } from "./AnalyzeTaskReadyWebhookDataStatus";
import { AnalyzeTaskWebhookError } from "./AnalyzeTaskWebhookError";
import { AnalyzeTaskWebhookDataBase } from "./AnalyzeTaskWebhookDataBase";

export const AnalyzeTaskReadyWebhookData: core.serialization.ObjectSchema<
    serializers.AnalyzeTaskReadyWebhookData.Raw,
    TwelvelabsApi.AnalyzeTaskReadyWebhookData
> = core.serialization
    .object({
        status: AnalyzeTaskReadyWebhookDataStatus,
        error: AnalyzeTaskWebhookError.optional(),
    })
    .extend(AnalyzeTaskWebhookDataBase);

export declare namespace AnalyzeTaskReadyWebhookData {
    export interface Raw extends AnalyzeTaskWebhookDataBase.Raw {
        status: AnalyzeTaskReadyWebhookDataStatus.Raw;
        error?: AnalyzeTaskWebhookError.Raw | null;
    }
}
