/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const AnalyzeTaskWebhookInfo: core.serialization.ObjectSchema<
    serializers.AnalyzeTaskWebhookInfo.Raw,
    TwelvelabsApi.AnalyzeTaskWebhookInfo
> = core.serialization.object({
    url: core.serialization.string(),
    delivered: core.serialization.boolean(),
    attempts: core.serialization.number(),
    lastError: core.serialization.property("last_error", core.serialization.string().optional()),
});

export declare namespace AnalyzeTaskWebhookInfo {
    export interface Raw {
        url: string;
        delivered: boolean;
        attempts: number;
        last_error?: string | null;
    }
}
