/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { AnalyzeTaskWebhookInfo } from "./AnalyzeTaskWebhookInfo";
import { AnalyzeBatchSummary } from "./AnalyzeBatchSummary";

export const AnalyzeBatchStatusResponse: core.serialization.ObjectSchema<
    serializers.AnalyzeBatchStatusResponse.Raw,
    TwelvelabsApi.AnalyzeBatchStatusResponse
> = core.serialization
    .object({
        queuedItems: core.serialization.property("queued_items", core.serialization.number()),
        processingItems: core.serialization.property("processing_items", core.serialization.number()),
        readyItems: core.serialization.property("ready_items", core.serialization.number()),
        failedItems: core.serialization.property("failed_items", core.serialization.number()),
        canceledItems: core.serialization.property("canceled_items", core.serialization.number()),
        webhooks: core.serialization.list(AnalyzeTaskWebhookInfo).optional(),
    })
    .extend(AnalyzeBatchSummary);

export declare namespace AnalyzeBatchStatusResponse {
    export interface Raw extends AnalyzeBatchSummary.Raw {
        queued_items: number;
        processing_items: number;
        ready_items: number;
        failed_items: number;
        canceled_items: number;
        webhooks?: AnalyzeTaskWebhookInfo.Raw[] | null;
    }
}
