/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const AnalyzeBatchSummaryAnalysisMode: core.serialization.Schema<
    serializers.AnalyzeBatchSummaryAnalysisMode.Raw,
    TwelvelabsApi.AnalyzeBatchSummaryAnalysisMode
> = core.serialization.enum_(["general", "time_based_metadata"]);

export declare namespace AnalyzeBatchSummaryAnalysisMode {
    export type Raw = "general" | "time_based_metadata";
}
