/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const AnalyzeTaskWebhookVideoSourceSystemMetadata: core.serialization.ObjectSchema<
    serializers.AnalyzeTaskWebhookVideoSourceSystemMetadata.Raw,
    TwelvelabsApi.AnalyzeTaskWebhookVideoSourceSystemMetadata
> = core.serialization.object({
    duration: core.serialization.number(),
});

export declare namespace AnalyzeTaskWebhookVideoSourceSystemMetadata {
    export interface Raw {
        duration: number;
    }
}
