/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { AnalyzeTaskResponseRequestParamsResponseFormatType } from "./AnalyzeTaskResponseRequestParamsResponseFormatType";
import { AnalyzeTaskResponseRequestParamsResponseFormatSegmentDefinitionsItem } from "./AnalyzeTaskResponseRequestParamsResponseFormatSegmentDefinitionsItem";

export const AnalyzeTaskResponseRequestParamsResponseFormat: core.serialization.ObjectSchema<
    serializers.AnalyzeTaskResponseRequestParamsResponseFormat.Raw,
    TwelvelabsApi.AnalyzeTaskResponseRequestParamsResponseFormat
> = core.serialization.object({
    type: AnalyzeTaskResponseRequestParamsResponseFormatType.optional(),
    segmentDefinitions: core.serialization.property(
        "segment_definitions",
        core.serialization.list(AnalyzeTaskResponseRequestParamsResponseFormatSegmentDefinitionsItem).optional(),
    ),
});

export declare namespace AnalyzeTaskResponseRequestParamsResponseFormat {
    export interface Raw {
        type?: AnalyzeTaskResponseRequestParamsResponseFormatType.Raw | null;
        segment_definitions?: AnalyzeTaskResponseRequestParamsResponseFormatSegmentDefinitionsItem.Raw[] | null;
    }
}
