/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const AnalyzeTaskError: core.serialization.ObjectSchema<
    serializers.AnalyzeTaskError.Raw,
    TwelvelabsApi.AnalyzeTaskError
> = core.serialization.object({
    code: core.serialization.string().optional(),
    message: core.serialization.string(),
});

export declare namespace AnalyzeTaskError {
    export interface Raw {
        code?: string | null;
        message: string;
    }
}
