/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const AnalyzeTaskReadyWebhookDataStatus: core.serialization.Schema<
    serializers.AnalyzeTaskReadyWebhookDataStatus.Raw,
    TwelvelabsApi.AnalyzeTaskReadyWebhookDataStatus
> = core.serialization.enum_(["ready"]);

export declare namespace AnalyzeTaskReadyWebhookDataStatus {
    export type Raw = "ready";
}
