/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const AnalyzeTaskWebhookError: core.serialization.ObjectSchema<
    serializers.AnalyzeTaskWebhookError.Raw,
    TwelvelabsApi.AnalyzeTaskWebhookError
> = core.serialization.object({
    message: core.serialization.string(),
});

export declare namespace AnalyzeTaskWebhookError {
    export interface Raw {
        message: string;
    }
}
