/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const AnalyzeTaskFailedWebhookDataStatus: core.serialization.Schema<
    serializers.AnalyzeTaskFailedWebhookDataStatus.Raw,
    TwelvelabsApi.AnalyzeTaskFailedWebhookDataStatus
> = core.serialization.enum_(["failed"]);

export declare namespace AnalyzeTaskFailedWebhookDataStatus {
    export type Raw = "failed";
}
