/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const AnalyzeTaskMediaSource: core.serialization.ObjectSchema<
    serializers.AnalyzeTaskMediaSource.Raw,
    TwelvelabsApi.AnalyzeTaskMediaSource
> = core.serialization.object({
    name: core.serialization.string(),
    mediaType: core.serialization.property("media_type", core.serialization.string()),
    url: core.serialization.string().optional(),
    assetId: core.serialization.property("asset_id", core.serialization.string().optional()),
});

export declare namespace AnalyzeTaskMediaSource {
    export interface Raw {
        name: string;
        media_type: string;
        url?: string | null;
        asset_id?: string | null;
    }
}
