/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { AnalyzeTaskWebhookVideoSource } from "./AnalyzeTaskWebhookVideoSource";

export const AnalyzeTaskWebhookDataBase: core.serialization.ObjectSchema<
    serializers.AnalyzeTaskWebhookDataBase.Raw,
    TwelvelabsApi.AnalyzeTaskWebhookDataBase
> = core.serialization.object({
    id: core.serialization.string(),
    customId: core.serialization.property("custom_id", core.serialization.string().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.date()),
    videoSource: core.serialization.property("video_source", AnalyzeTaskWebhookVideoSource.optional()),
});

export declare namespace AnalyzeTaskWebhookDataBase {
    export interface Raw {
        id: string;
        custom_id?: string | null;
        created_at: string;
        video_source?: AnalyzeTaskWebhookVideoSource.Raw | null;
    }
}
