/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { AssetHlsStatus } from "./AssetHlsStatus";

export const AssetHls: core.serialization.ObjectSchema<serializers.AssetHls.Raw, TwelvelabsApi.AssetHls> =
    core.serialization.object({
        manifestUrl: core.serialization.property("manifest_url", core.serialization.string().optional()),
        status: AssetHlsStatus.optional(),
    });

export declare namespace AssetHls {
    export interface Raw {
        manifest_url?: string | null;
        status?: AssetHlsStatus.Raw | null;
    }
}
