/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const AssetMethod: core.serialization.Schema<serializers.AssetMethod.Raw, TwelvelabsApi.AssetMethod> =
    core.serialization.enum_(["direct", "url"]);

export declare namespace AssetMethod {
    export type Raw = "direct" | "url";
}
