/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { AssetSourceDetailsProvider } from "./AssetSourceDetailsProvider";

export const AssetSourceDetails: core.serialization.ObjectSchema<
    serializers.AssetSourceDetails.Raw,
    TwelvelabsApi.AssetSourceDetails
> = core.serialization.object({
    provider: AssetSourceDetailsProvider.optional(),
    sourceId: core.serialization.property("source_id", core.serialization.string().optional()),
    originalFilename: core.serialization.property("original_filename", core.serialization.string().optional()),
    sourceLink: core.serialization.property("source_link", core.serialization.string().optional()),
});

export declare namespace AssetSourceDetails {
    export interface Raw {
        provider?: AssetSourceDetailsProvider.Raw | null;
        source_id?: string | null;
        original_filename?: string | null;
        source_link?: string | null;
    }
}
