/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const AsyncResponseFormatSegmentTimeFormat: core.serialization.Schema<
    serializers.AsyncResponseFormatSegmentTimeFormat.Raw,
    TwelvelabsApi.AsyncResponseFormatSegmentTimeFormat
> = core.serialization.enum_(["seconds", "hh:mm:ss", "hh:mm:ss.fff"]);

export declare namespace AsyncResponseFormatSegmentTimeFormat {
    export type Raw = "seconds" | "hh:mm:ss" | "hh:mm:ss.fff";
}
