/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const AsyncAudioInputRequestEmbeddingScopeItem: core.serialization.Schema<
    serializers.AsyncAudioInputRequestEmbeddingScopeItem.Raw,
    TwelvelabsApi.AsyncAudioInputRequestEmbeddingScopeItem
> = core.serialization.enum_(["clip", "local", "asset"]);

export declare namespace AsyncAudioInputRequestEmbeddingScopeItem {
    export type Raw = "clip" | "local" | "asset";
}
