/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { VideoSegmentation } from "./VideoSegmentation";
import { AsyncTemporalSegmentation } from "./AsyncTemporalSegmentation";

export const AsyncVideoInputRequestSegmentation: core.serialization.Schema<
    serializers.AsyncVideoInputRequestSegmentation.Raw,
    TwelvelabsApi.AsyncVideoInputRequestSegmentation
> = core.serialization.undiscriminatedUnion([VideoSegmentation, AsyncTemporalSegmentation]);

export declare namespace AsyncVideoInputRequestSegmentation {
    export type Raw = VideoSegmentation.Raw | AsyncTemporalSegmentation.Raw;
}
