/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { AsyncResponseFormatType } from "./AsyncResponseFormatType";
import { SegmentDefinition } from "./SegmentDefinition";

export const AsyncResponseFormat: core.serialization.ObjectSchema<
    serializers.AsyncResponseFormat.Raw,
    TwelvelabsApi.AsyncResponseFormat
> = core.serialization.object({
    type: AsyncResponseFormatType,
    jsonSchema: core.serialization.property(
        "json_schema",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    ),
    segmentDefinitions: core.serialization.property(
        "segment_definitions",
        core.serialization.list(SegmentDefinition).optional(),
    ),
});

export declare namespace AsyncResponseFormat {
    export interface Raw {
        type: AsyncResponseFormatType.Raw;
        json_schema?: Record<string, unknown> | null;
        segment_definitions?: SegmentDefinition.Raw[] | null;
    }
}
