/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { BaseSegment } from "./BaseSegment";

export const AudioSegment: core.serialization.ObjectSchema<serializers.AudioSegment.Raw, TwelvelabsApi.AudioSegment> =
    core.serialization
        .object({
            startOffsetSec: core.serialization.property("start_offset_sec", core.serialization.number().optional()),
        })
        .extend(BaseSegment);

export declare namespace AudioSegment {
    export interface Raw extends BaseSegment.Raw {
        start_offset_sec?: number | null;
    }
}
