/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const AudioInputRequestEmbeddingScopeItem: core.serialization.Schema<
    serializers.AudioInputRequestEmbeddingScopeItem.Raw,
    TwelvelabsApi.AudioInputRequestEmbeddingScopeItem
> = core.serialization.enum_(["clip", "asset"]);

export declare namespace AudioInputRequestEmbeddingScopeItem {
    export type Raw = "clip" | "asset";
}
