/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const AudioInputRequestEmbeddingOptionItem: core.serialization.Schema<
    serializers.AudioInputRequestEmbeddingOptionItem.Raw,
    TwelvelabsApi.AudioInputRequestEmbeddingOptionItem
> = core.serialization.enum_(["audio", "transcription"]);

export declare namespace AudioInputRequestEmbeddingOptionItem {
    export type Raw = "audio" | "transcription";
}
