/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const ConnectionProvider: core.serialization.Schema<
    serializers.ConnectionProvider.Raw,
    TwelvelabsApi.ConnectionProvider
> = core.serialization.enum_(["google_drive"]);

export declare namespace ConnectionProvider {
    export type Raw = "google_drive";
}
