/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { AnalyzeTaskStatus } from "./AnalyzeTaskStatus";

export const CreateAnalyzeTaskResponse: core.serialization.ObjectSchema<
    serializers.CreateAnalyzeTaskResponse.Raw,
    TwelvelabsApi.CreateAnalyzeTaskResponse
> = core.serialization.object({
    taskId: core.serialization.property("task_id", core.serialization.string()),
    status: AnalyzeTaskStatus,
});

export declare namespace CreateAnalyzeTaskResponse {
    export interface Raw {
        task_id: string;
        status: AnalyzeTaskStatus.Raw;
    }
}
