/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { PresignedUrlChunk } from "./PresignedUrlChunk";

export const CreateAssetUploadResponse: core.serialization.ObjectSchema<
    serializers.CreateAssetUploadResponse.Raw,
    TwelvelabsApi.CreateAssetUploadResponse
> = core.serialization.object({
    uploadId: core.serialization.property("upload_id", core.serialization.string().optional()),
    assetId: core.serialization.property("asset_id", core.serialization.string().optional()),
    uploadUrls: core.serialization.property("upload_urls", core.serialization.list(PresignedUrlChunk).optional()),
    uploadHeaders: core.serialization.property(
        "upload_headers",
        core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
    ),
    chunkSize: core.serialization.property("chunk_size", core.serialization.number().optional()),
    totalChunks: core.serialization.property("total_chunks", core.serialization.number().optional()),
    expiresAt: core.serialization.property("expires_at", core.serialization.date().optional()),
});

export declare namespace CreateAssetUploadResponse {
    export interface Raw {
        upload_id?: string | null;
        asset_id?: string | null;
        upload_urls?: PresignedUrlChunk.Raw[] | null;
        upload_headers?: Record<string, string> | null;
        chunk_size?: number | null;
        total_chunks?: number | null;
        expires_at?: string | null;
    }
}
