/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const CreatedAt: core.serialization.Schema<serializers.CreatedAt.Raw, TwelvelabsApi.CreatedAt> =
    core.serialization.date();

export declare namespace CreatedAt {
    export type Raw = string;
}
