/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { EmbeddingDataEmbeddingOption } from "./EmbeddingDataEmbeddingOption";
import { EmbeddingDataEmbeddingScope } from "./EmbeddingDataEmbeddingScope";

export const EmbeddingData: core.serialization.ObjectSchema<
    serializers.EmbeddingData.Raw,
    TwelvelabsApi.EmbeddingData
> = core.serialization.object({
    embedding: core.serialization.list(core.serialization.number()),
    embeddingOption: core.serialization.property("embedding_option", EmbeddingDataEmbeddingOption.optional()),
    embeddingScope: core.serialization.property("embedding_scope", EmbeddingDataEmbeddingScope.optional()),
    startSec: core.serialization.property("start_sec", core.serialization.number().optional()),
    endSec: core.serialization.property("end_sec", core.serialization.number().optional()),
});

export declare namespace EmbeddingData {
    export interface Raw {
        embedding: number[];
        embedding_option?: EmbeddingDataEmbeddingOption.Raw | null;
        embedding_scope?: EmbeddingDataEmbeddingScope.Raw | null;
        start_sec?: number | null;
        end_sec?: number | null;
    }
}
