/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const EmbeddingVideoMetadataEmbeddingScopesItem: core.serialization.Schema<
    serializers.EmbeddingVideoMetadataEmbeddingScopesItem.Raw,
    TwelvelabsApi.EmbeddingVideoMetadataEmbeddingScopesItem
> = core.serialization.enum_(["clip", "asset"]);

export declare namespace EmbeddingVideoMetadataEmbeddingScopesItem {
    export type Raw = "clip" | "asset";
}
