/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { EmbeddingTaskResponseStatus } from "./EmbeddingTaskResponseStatus";
import { CreatedAt } from "./CreatedAt";
import { UpdatedAt } from "./UpdatedAt";
import { EmbeddingData } from "./EmbeddingData";
import { EmbeddingTaskMediaMetadata } from "./EmbeddingTaskMediaMetadata";

export const EmbeddingTaskResponse: core.serialization.ObjectSchema<
    serializers.EmbeddingTaskResponse.Raw,
    TwelvelabsApi.EmbeddingTaskResponse
> = core.serialization.object({
    id: core.serialization.property("_id", core.serialization.string()),
    status: EmbeddingTaskResponseStatus,
    createdAt: core.serialization.property("created_at", CreatedAt.optional()),
    updatedAt: core.serialization.property("updated_at", UpdatedAt.optional()),
    data: core.serialization.list(EmbeddingData).optional(),
    metadata: EmbeddingTaskMediaMetadata.optional(),
});

export declare namespace EmbeddingTaskResponse {
    export interface Raw {
        _id: string;
        status: EmbeddingTaskResponseStatus.Raw;
        created_at?: CreatedAt.Raw | null;
        updated_at?: UpdatedAt.Raw | null;
        data?: EmbeddingData.Raw[] | null;
        metadata?: EmbeddingTaskMediaMetadata.Raw | null;
    }
}
