/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const EmbeddingImageMetadata: core.serialization.ObjectSchema<
    serializers.EmbeddingImageMetadata.Raw,
    TwelvelabsApi.EmbeddingImageMetadata
> = core.serialization.object({
    inputUrl: core.serialization.property("input_url", core.serialization.string().optional()),
    inputFilename: core.serialization.property("input_filename", core.serialization.string().optional()),
});

export declare namespace EmbeddingImageMetadata {
    export interface Raw {
        input_url?: string | null;
        input_filename?: string | null;
    }
}
