/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const EmbeddingDataQuadrant: core.serialization.Schema<
    serializers.EmbeddingDataQuadrant.Raw,
    TwelvelabsApi.EmbeddingDataQuadrant
> = core.serialization.enum_(["top_left", "top_right", "bottom_left", "bottom_right"]);

export declare namespace EmbeddingDataQuadrant {
    export type Raw = "top_left" | "top_right" | "bottom_left" | "bottom_right";
}
