/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const EntityStatus: core.serialization.Schema<serializers.EntityStatus.Raw, TwelvelabsApi.EntityStatus> =
    core.serialization.enum_(["processing", "ready"]);

export declare namespace EntityStatus {
    export type Raw = "processing" | "ready";
}
