/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const ForbiddenErrorBody: core.serialization.ObjectSchema<
    serializers.ForbiddenErrorBody.Raw,
    TwelvelabsApi.ForbiddenErrorBody
> = core.serialization.object({
    code: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
    docsUrl: core.serialization.property("docs_url", core.serialization.string().optional()),
});

export declare namespace ForbiddenErrorBody {
    export interface Raw {
        code?: string | null;
        message?: string | null;
        docs_url?: string | null;
    }
}
