/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { HlsObjectStatus } from "./HlsObjectStatus";

export const HlsObject: core.serialization.ObjectSchema<serializers.HlsObject.Raw, TwelvelabsApi.HlsObject> =
    core.serialization.object({
        videoUrl: core.serialization.property("video_url", core.serialization.string().optional()),
        thumbnailUrls: core.serialization.property(
            "thumbnail_urls",
            core.serialization.list(core.serialization.string()).optional(),
        ),
        status: HlsObjectStatus.optional(),
        updatedAt: core.serialization.property("updated_at", core.serialization.string().optional()),
    });

export declare namespace HlsObject {
    export interface Raw {
        video_url?: string | null;
        thumbnail_urls?: string[] | null;
        status?: HlsObjectStatus.Raw | null;
        updated_at?: string | null;
    }
}
