/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { BaseEmbeddingMetadata } from "./BaseEmbeddingMetadata";

export const ImageEmbeddingMetadata: core.serialization.ObjectSchema<
    serializers.ImageEmbeddingMetadata.Raw,
    TwelvelabsApi.ImageEmbeddingMetadata
> = core.serialization
    .object({
        imageEmbeddingOption: core.serialization.property(
            "image_embedding_option",
            core.serialization.list(core.serialization.string()).optional(),
        ),
        imageEmbeddingScope: core.serialization.property(
            "image_embedding_scope",
            core.serialization.list(core.serialization.string()).optional(),
        ),
    })
    .extend(BaseEmbeddingMetadata);

export declare namespace ImageEmbeddingMetadata {
    export interface Raw extends BaseEmbeddingMetadata.Raw {
        image_embedding_option?: string[] | null;
        image_embedding_scope?: string[] | null;
    }
}
