/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { ImageSearchSystemMetadata } from "./ImageSearchSystemMetadata";
import { UserMetadata } from "./UserMetadata";

export const ImageSearchItemMetadata: core.serialization.ObjectSchema<
    serializers.ImageSearchItemMetadata.Raw,
    TwelvelabsApi.ImageSearchItemMetadata
> = core.serialization.object({
    system: ImageSearchSystemMetadata.optional(),
    user: UserMetadata.optional(),
});

export declare namespace ImageSearchItemMetadata {
    export interface Raw {
        system?: ImageSearchSystemMetadata.Raw | null;
        user?: UserMetadata.Raw | null;
    }
}
