/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const ImageMetadata: core.serialization.ObjectSchema<
    serializers.ImageMetadata.Raw,
    TwelvelabsApi.ImageMetadata
> = core.serialization.object({
    filename: core.serialization.string().optional(),
    width: core.serialization.number().optional(),
    height: core.serialization.number().optional(),
    codecName: core.serialization.property("codec_name", core.serialization.string().optional()),
    size: core.serialization.number().optional(),
});

export declare namespace ImageMetadata {
    export interface Raw {
        filename?: string | null;
        width?: number | null;
        height?: number | null;
        codec_name?: string | null;
        size?: number | null;
    }
}
