/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const ImportProvider: core.serialization.Schema<serializers.ImportProvider.Raw, TwelvelabsApi.ImportProvider> =
    core.serialization.enum_(["google_drive"]);

export declare namespace ImportProvider {
    export type Raw = "google_drive";
}
