/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { ImportItem } from "./ImportItem";

export const ImportResult: core.serialization.ObjectSchema<serializers.ImportResult.Raw, TwelvelabsApi.ImportResult> =
    core.serialization.object({
        id: core.serialization.property("_id", core.serialization.string().optional()),
        hasFailures: core.serialization.property("has_failures", core.serialization.boolean().optional()),
        items: core.serialization.list(ImportItem).optional(),
    });

export declare namespace ImportResult {
    export interface Raw {
        _id?: string | null;
        has_failures?: boolean | null;
        items?: ImportItem.Raw[] | null;
    }
}
