/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { ImportProvider } from "./ImportProvider";

export const Import: core.serialization.ObjectSchema<serializers.Import.Raw, TwelvelabsApi.Import> =
    core.serialization.object({
        id: core.serialization.property("_id", core.serialization.string().optional()),
        connectionId: core.serialization.property("connection_id", core.serialization.string().optional()),
        provider: ImportProvider.optional(),
        customId: core.serialization.property("custom_id", core.serialization.string().optional()),
        itemCount: core.serialization.property("item_count", core.serialization.number().optional()),
        createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
    });

export declare namespace Import {
    export interface Raw {
        _id?: string | null;
        connection_id?: string | null;
        provider?: ImportProvider.Raw | null;
        custom_id?: string | null;
        item_count?: number | null;
        created_at?: string | null;
    }
}
