/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const ImportLogVideoStatus: core.serialization.ObjectSchema<
    serializers.ImportLogVideoStatus.Raw,
    TwelvelabsApi.ImportLogVideoStatus
> = core.serialization.object({
    ready: core.serialization.number(),
    validating: core.serialization.number(),
    queued: core.serialization.number(),
    pending: core.serialization.number(),
    indexing: core.serialization.number(),
    failed: core.serialization.number(),
});

export declare namespace ImportLogVideoStatus {
    export interface Raw {
        ready: number;
        validating: number;
        queued: number;
        pending: number;
        indexing: number;
        failed: number;
    }
}
