/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { HlsObject } from "./HlsObject";
import { IndexedAssetDetailedEmbedding } from "./IndexedAssetDetailedEmbedding";
import { TranscriptionData } from "./TranscriptionData";
import { IndexedAsset } from "./IndexedAsset";
import { TranscriptionDataItem } from "./TranscriptionDataItem";

export const IndexedAssetDetailed: core.serialization.ObjectSchema<
    serializers.IndexedAssetDetailed.Raw,
    TwelvelabsApi.IndexedAssetDetailed
> = core.serialization
    .object({
        userMetadata: core.serialization.property(
            "user_metadata",
            core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        ),
        hls: HlsObject.optional(),
        embedding: IndexedAssetDetailedEmbedding.optional(),
        transcription: TranscriptionData.optional(),
    })
    .extend(IndexedAsset);

export declare namespace IndexedAssetDetailed {
    export interface Raw extends IndexedAsset.Raw {
        user_metadata?: Record<string, unknown> | null;
        hls?: HlsObject.Raw | null;
        embedding?: IndexedAssetDetailedEmbedding.Raw | null;
        transcription?: TranscriptionData.Raw | null;
    }
}
