/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const IndexedAssetsListRequestSize: core.serialization.ObjectSchema<
    serializers.IndexedAssetsListRequestSize.Raw,
    TwelvelabsApi.IndexedAssetsListRequestSize
> = core.serialization.object({
    gte: core.serialization.number().optional(),
    lte: core.serialization.number().optional(),
});

export declare namespace IndexedAssetsListRequestSize {
    export interface Raw {
        gte?: number | null;
        lte?: number | null;
    }
}
