/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { EnrichmentConfig } from "./EnrichmentConfig";

export const IngestionConfig: core.serialization.ObjectSchema<
    serializers.IngestionConfig.Raw,
    TwelvelabsApi.IngestionConfig
> = core.serialization.object({
    enrichmentConfig: core.serialization.property("enrichment_config", EnrichmentConfig),
});

export declare namespace IngestionConfig {
    export interface Raw {
        enrichment_config: EnrichmentConfig.Raw;
    }
}
