/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const MediaSource: core.serialization.ObjectSchema<serializers.MediaSource.Raw, TwelvelabsApi.MediaSource> =
    core.serialization.object({
        base64String: core.serialization.property("base64_string", core.serialization.string().optional()),
        url: core.serialization.string().optional(),
        assetId: core.serialization.property("asset_id", core.serialization.string().optional()),
    });

export declare namespace MediaSource {
    export interface Raw {
        base64_string?: string | null;
        url?: string | null;
        asset_id?: string | null;
    }
}
