/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const One: core.serialization.ObjectSchema<serializers.One.Raw, TwelvelabsApi.One> = core.serialization.object({
    assetId: core.serialization.property("asset_id", core.serialization.string()),
});

export declare namespace One {
    export interface Raw {
        asset_id: string;
    }
}
