/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const RedirectUri: core.serialization.ObjectSchema<serializers.RedirectUri.Raw, TwelvelabsApi.RedirectUri> =
    core.serialization.object({
        id: core.serialization.property("_id", core.serialization.string().optional()),
        redirectUri: core.serialization.property("redirect_uri", core.serialization.string().optional()),
        createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
    });

export declare namespace RedirectUri {
    export interface Raw {
        _id?: string | null;
        redirect_uri?: string | null;
        created_at?: string | null;
    }
}
