/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { PresignedUrlChunk } from "./PresignedUrlChunk";
import { ExpiresAt } from "./ExpiresAt";

export const RequestAdditionalPresignedUrLsResponse: core.serialization.ObjectSchema<
    serializers.RequestAdditionalPresignedUrLsResponse.Raw,
    TwelvelabsApi.RequestAdditionalPresignedUrLsResponse
> = core.serialization.object({
    uploadId: core.serialization.property("upload_id", core.serialization.string().optional()),
    startIndex: core.serialization.property("start_index", core.serialization.number().optional()),
    count: core.serialization.number().optional(),
    uploadUrls: core.serialization.property("upload_urls", core.serialization.list(PresignedUrlChunk).optional()),
    generatedAt: core.serialization.property("generated_at", core.serialization.date().optional()),
    expiresAt: core.serialization.property("expires_at", ExpiresAt.optional()),
});

export declare namespace RequestAdditionalPresignedUrLsResponse {
    export interface Raw {
        upload_id?: string | null;
        start_index?: number | null;
        count?: number | null;
        upload_urls?: PresignedUrlChunk.Raw[] | null;
        generated_at?: string | null;
        expires_at?: ExpiresAt.Raw | null;
    }
}
