/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { ResponseStreamEventBase } from "./ResponseStreamEventBase";

export const ResponseStreamOutputTextDoneEvent: core.serialization.ObjectSchema<
    serializers.ResponseStreamOutputTextDoneEvent.Raw,
    TwelvelabsApi.ResponseStreamOutputTextDoneEvent
> = core.serialization
    .object({
        itemId: core.serialization.property("item_id", core.serialization.string().optional()),
        outputIndex: core.serialization.property("output_index", core.serialization.number().optional()),
        contentIndex: core.serialization.property("content_index", core.serialization.number().optional()),
        text: core.serialization.string().optional(),
    })
    .extend(ResponseStreamEventBase);

export declare namespace ResponseStreamOutputTextDoneEvent {
    export interface Raw extends ResponseStreamEventBase.Raw {
        item_id?: string | null;
        output_index?: number | null;
        content_index?: number | null;
        text?: string | null;
    }
}
