/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const ResponseFormat: core.serialization.ObjectSchema<
    serializers.ResponseFormat.Raw,
    TwelvelabsApi.ResponseFormat
> = core.serialization.object({
    type: core.serialization.stringLiteral("json_schema"),
    jsonSchema: core.serialization.property(
        "json_schema",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    ),
});

export declare namespace ResponseFormat {
    export interface Raw {
        type: "json_schema";
        json_schema: Record<string, unknown>;
    }
}
