/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { ResponseObjectType } from "./ResponseObjectType";
import { ResponseObjectObject } from "./ResponseObjectObject";
import { ResponseStatus } from "./ResponseStatus";
import { ResponseIncompleteDetails } from "./ResponseIncompleteDetails";
import { ResponseOutputItem } from "./ResponseOutputItem";
import { ResponseUsage } from "./ResponseUsage";

export const ResponseObject: core.serialization.ObjectSchema<
    serializers.ResponseObject.Raw,
    TwelvelabsApi.ResponseObject
> = core.serialization.object({
    id: core.serialization.string().optional(),
    knowledgeStoreId: core.serialization.property("knowledge_store_id", core.serialization.string().optional()),
    sessionId: core.serialization.property("session_id", core.serialization.string().optional()),
    type: ResponseObjectType.optional(),
    object: ResponseObjectObject.optional(),
    status: ResponseStatus.optional(),
    incompleteDetails: core.serialization.property("incomplete_details", ResponseIncompleteDetails.optional()),
    output: core.serialization.list(ResponseOutputItem).optional(),
    usage: ResponseUsage.optional(),
    createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
});

export declare namespace ResponseObject {
    export interface Raw {
        id?: string | null;
        knowledge_store_id?: string | null;
        session_id?: string | null;
        type?: ResponseObjectType.Raw | null;
        object?: ResponseObjectObject.Raw | null;
        status?: ResponseStatus.Raw | null;
        incomplete_details?: ResponseIncompleteDetails.Raw | null;
        output?: ResponseOutputItem.Raw[] | null;
        usage?: ResponseUsage.Raw | null;
        created_at?: string | null;
    }
}
