/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const ResponseStatus: core.serialization.Schema<serializers.ResponseStatus.Raw, TwelvelabsApi.ResponseStatus> =
    core.serialization.enum_(["completed", "failed", "in_progress", "incomplete"]);

export declare namespace ResponseStatus {
    export type Raw = "completed" | "failed" | "in_progress" | "incomplete";
}
