/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { ResponseOutputContentPart } from "./ResponseOutputContentPart";
import { ResponseStreamEventBase } from "./ResponseStreamEventBase";

export const ResponseStreamContentPartAddedEvent: core.serialization.ObjectSchema<
    serializers.ResponseStreamContentPartAddedEvent.Raw,
    TwelvelabsApi.ResponseStreamContentPartAddedEvent
> = core.serialization
    .object({
        itemId: core.serialization.property("item_id", core.serialization.string().optional()),
        outputIndex: core.serialization.property("output_index", core.serialization.number().optional()),
        contentIndex: core.serialization.property("content_index", core.serialization.number().optional()),
        part: ResponseOutputContentPart.optional(),
    })
    .extend(ResponseStreamEventBase);

export declare namespace ResponseStreamContentPartAddedEvent {
    export interface Raw extends ResponseStreamEventBase.Raw {
        item_id?: string | null;
        output_index?: number | null;
        content_index?: number | null;
        part?: ResponseOutputContentPart.Raw | null;
    }
}
