/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { ResponseOutputItemType } from "./ResponseOutputItemType";
import { ResponseStatus } from "./ResponseStatus";
import { ResponseOutputItemRole } from "./ResponseOutputItemRole";
import { ResponseOutputContentPart } from "./ResponseOutputContentPart";

export const ResponseOutputItem: core.serialization.ObjectSchema<
    serializers.ResponseOutputItem.Raw,
    TwelvelabsApi.ResponseOutputItem
> = core.serialization.object({
    type: ResponseOutputItemType,
    id: core.serialization.string(),
    status: ResponseStatus,
    role: ResponseOutputItemRole.optional(),
    phase: core.serialization.string().optional(),
    content: core.serialization.list(ResponseOutputContentPart).optional(),
    name: core.serialization.string().optional(),
    callId: core.serialization.property("call_id", core.serialization.string().optional()),
    arguments: core.serialization.string().optional(),
    output: core.serialization.string().optional(),
});

export declare namespace ResponseOutputItem {
    export interface Raw {
        type: ResponseOutputItemType.Raw;
        id: string;
        status: ResponseStatus.Raw;
        role?: ResponseOutputItemRole.Raw | null;
        phase?: string | null;
        content?: ResponseOutputContentPart.Raw[] | null;
        name?: string | null;
        call_id?: string | null;
        arguments?: string | null;
        output?: string | null;
    }
}
