/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const ResponseUsage: core.serialization.ObjectSchema<
    serializers.ResponseUsage.Raw,
    TwelvelabsApi.ResponseUsage
> = core.serialization.object({
    inputTokens: core.serialization.property("input_tokens", core.serialization.number().optional()),
    outputTokens: core.serialization.property("output_tokens", core.serialization.number().optional()),
});

export declare namespace ResponseUsage {
    export interface Raw {
        input_tokens?: number | null;
        output_tokens?: number | null;
    }
}
