/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { VideoSearchHit } from "./VideoSearchHit";
import { ImageSearchHit } from "./ImageSearchHit";

export const SearchKnowledgeStoreHit: core.serialization.Schema<
    serializers.SearchKnowledgeStoreHit.Raw,
    TwelvelabsApi.SearchKnowledgeStoreHit
> = core.serialization
    .union(core.serialization.discriminant("assetType", "asset_type"), {
        video: VideoSearchHit,
        image: ImageSearchHit,
    })
    .transform<TwelvelabsApi.SearchKnowledgeStoreHit>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace SearchKnowledgeStoreHit {
    export type Raw = SearchKnowledgeStoreHit.Video | SearchKnowledgeStoreHit.Image;

    export interface Video extends VideoSearchHit.Raw {
        asset_type: "video";
    }

    export interface Image extends ImageSearchHit.Raw {
        asset_type: "image";
    }
}
