/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { SearchKnowledgeStoreHit } from "./SearchKnowledgeStoreHit";
import { NextPageToken } from "./NextPageToken";
import { SearchKnowledgeStoreOptions } from "./SearchKnowledgeStoreOptions";

export const SearchKnowledgeStoreResponse: core.serialization.ObjectSchema<
    serializers.SearchKnowledgeStoreResponse.Raw,
    TwelvelabsApi.SearchKnowledgeStoreResponse
> = core.serialization.object({
    data: core.serialization.list(SearchKnowledgeStoreHit),
    nextPageToken: core.serialization.property("next_page_token", NextPageToken.optional()),
    effectiveSearchOptions: core.serialization.property("effective_search_options", SearchKnowledgeStoreOptions),
});

export declare namespace SearchKnowledgeStoreResponse {
    export interface Raw {
        data: SearchKnowledgeStoreHit.Raw[];
        next_page_token?: NextPageToken.Raw | null;
        effective_search_options: SearchKnowledgeStoreOptions.Raw;
    }
}
