/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const SearchPool: core.serialization.ObjectSchema<serializers.SearchPool.Raw, TwelvelabsApi.SearchPool> =
    core.serialization.object({
        totalCount: core.serialization.property("total_count", core.serialization.number().optional()),
        totalDuration: core.serialization.property("total_duration", core.serialization.number().optional()),
        indexId: core.serialization.property("index_id", core.serialization.string().optional()),
    });

export declare namespace SearchPool {
    export interface Raw {
        total_count?: number | null;
        total_duration?: number | null;
        index_id?: string | null;
    }
}
