/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { AssetTypeFilter } from "./AssetTypeFilter";
import { ItemIdFilter } from "./ItemIdFilter";

export const SearchKnowledgeStoreFilter: core.serialization.ObjectSchema<
    serializers.SearchKnowledgeStoreFilter.Raw,
    TwelvelabsApi.SearchKnowledgeStoreFilter
> = core.serialization.object({
    assetType: core.serialization.property("asset_type", AssetTypeFilter.optional()),
    itemId: core.serialization.property("item_id", ItemIdFilter.optional()),
});

export declare namespace SearchKnowledgeStoreFilter {
    export interface Raw {
        asset_type?: AssetTypeFilter.Raw | null;
        item_id?: ItemIdFilter.Raw | null;
    }
}
