/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const SegmentFieldItemsType: core.serialization.Schema<
    serializers.SegmentFieldItemsType.Raw,
    TwelvelabsApi.SegmentFieldItemsType
> = core.serialization.enum_(["string", "number", "boolean", "integer"]);

export declare namespace SegmentFieldItemsType {
    export type Raw = "string" | "number" | "boolean" | "integer";
}
