/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { SegmentFieldType } from "./SegmentFieldType";
import { SegmentFieldItems } from "./SegmentFieldItems";

export const SegmentField: core.serialization.ObjectSchema<serializers.SegmentField.Raw, TwelvelabsApi.SegmentField> =
    core.serialization.object({
        name: core.serialization.string(),
        type: SegmentFieldType,
        description: core.serialization.string(),
        enum: core.serialization.list(core.serialization.string()).optional(),
        items: SegmentFieldItems.optional(),
    });

export declare namespace SegmentField {
    export interface Raw {
        name: string;
        type: SegmentFieldType.Raw;
        description: string;
        enum?: string[] | null;
        items?: SegmentFieldItems.Raw | null;
    }
}
