/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { StreamEndResponseMetadata } from "./StreamEndResponseMetadata";

export const StreamEndResponse: core.serialization.ObjectSchema<
    serializers.StreamEndResponse.Raw,
    TwelvelabsApi.StreamEndResponse
> = core.serialization.object({
    eventType: core.serialization.property("event_type", core.serialization.string().optional()),
    metadata: StreamEndResponseMetadata.optional(),
});

export declare namespace StreamEndResponse {
    export interface Raw {
        event_type?: string | null;
        metadata?: StreamEndResponseMetadata.Raw | null;
    }
}
