/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { StreamStartResponseMetadata } from "./StreamStartResponseMetadata";

export const StreamStartResponse: core.serialization.ObjectSchema<
    serializers.StreamStartResponse.Raw,
    TwelvelabsApi.StreamStartResponse
> = core.serialization.object({
    metadata: StreamStartResponseMetadata.optional(),
});

export declare namespace StreamStartResponse {
    export interface Raw {
        metadata?: StreamStartResponseMetadata.Raw | null;
    }
}
