/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const StreamStartResponseMetadata: core.serialization.ObjectSchema<
    serializers.StreamStartResponseMetadata.Raw,
    TwelvelabsApi.StreamStartResponseMetadata
> = core.serialization.object({
    generationId: core.serialization.property("generation_id", core.serialization.string().optional()),
});

export declare namespace StreamStartResponseMetadata {
    export interface Raw {
        generation_id?: string | null;
    }
}
