/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const SummarizeSummaryResultSummarizeType: core.serialization.Schema<
    serializers.SummarizeSummaryResultSummarizeType.Raw,
    TwelvelabsApi.SummarizeSummaryResultSummarizeType
> = core.serialization.enum_(["summary"]);

export declare namespace SummarizeSummaryResultSummarizeType {
    export type Raw = "summary";
}
