/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { TokenUsage } from "./TokenUsage";

export const SummarizeSummaryResult: core.serialization.ObjectSchema<
    serializers.SummarizeSummaryResult.Raw,
    TwelvelabsApi.SummarizeSummaryResult
> = core.serialization.object({
    id: core.serialization.string().optional(),
    summary: core.serialization.string().optional(),
    usage: TokenUsage.optional(),
});

export declare namespace SummarizeSummaryResult {
    export interface Raw {
        id?: string | null;
        summary?: string | null;
        usage?: TokenUsage.Raw | null;
    }
}
