/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const SummarizeHighlightResultHighlightsItem: core.serialization.ObjectSchema<
    serializers.SummarizeHighlightResultHighlightsItem.Raw,
    TwelvelabsApi.SummarizeHighlightResultHighlightsItem
> = core.serialization.object({
    start: core.serialization.number().optional(),
    end: core.serialization.number().optional(),
    startSec: core.serialization.property("start_sec", core.serialization.number().optional()),
    endSec: core.serialization.property("end_sec", core.serialization.number().optional()),
    highlight: core.serialization.string().optional(),
    highlightSummary: core.serialization.property("highlight_summary", core.serialization.string().optional()),
});

export declare namespace SummarizeHighlightResultHighlightsItem {
    export interface Raw {
        start?: number | null;
        end?: number | null;
        start_sec?: number | null;
        end_sec?: number | null;
        highlight?: string | null;
        highlight_summary?: string | null;
    }
}
