/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const SyncResponseFormatType: core.serialization.Schema<
    serializers.SyncResponseFormatType.Raw,
    TwelvelabsApi.SyncResponseFormatType
> = core.serialization.enum_(["json_schema"]);

export declare namespace SyncResponseFormatType {
    export type Raw = "json_schema";
}
