/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { TemporalSegmentationDynamic } from "./TemporalSegmentationDynamic";
import { TemporalSegmentationFixed } from "./TemporalSegmentationFixed";

export const TemporalSegmentation: core.serialization.Schema<
    serializers.TemporalSegmentation.Raw,
    TwelvelabsApi.TemporalSegmentation
> = core.serialization
    .union("strategy", {
        dynamic: TemporalSegmentationDynamic,
        fixed: TemporalSegmentationFixed,
    })
    .transform<TwelvelabsApi.TemporalSegmentation>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace TemporalSegmentation {
    export type Raw = TemporalSegmentation.Dynamic | TemporalSegmentation.Fixed;

    export interface Dynamic extends TemporalSegmentationDynamic.Raw {
        strategy: "dynamic";
    }

    export interface Fixed extends TemporalSegmentationFixed.Raw {
        strategy: "fixed";
    }
}
