/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { TemporalSegmentationFixedFixed } from "./TemporalSegmentationFixedFixed";

export const TemporalSegmentationFixed: core.serialization.ObjectSchema<
    serializers.TemporalSegmentationFixed.Raw,
    TwelvelabsApi.TemporalSegmentationFixed
> = core.serialization.object({
    fixed: TemporalSegmentationFixedFixed,
});

export declare namespace TemporalSegmentationFixed {
    export interface Raw {
        fixed: TemporalSegmentationFixedFixed.Raw;
    }
}
