/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { BaseSegment } from "./BaseSegment";

export const TextEmbeddingResult: core.serialization.ObjectSchema<
    serializers.TextEmbeddingResult.Raw,
    TwelvelabsApi.TextEmbeddingResult
> = core.serialization.object({
    errorMessage: core.serialization.property("error_message", core.serialization.string().optional()),
    segments: core.serialization.list(BaseSegment).optional(),
});

export declare namespace TextEmbeddingResult {
    export interface Raw {
        error_message?: string | null;
        segments?: BaseSegment.Raw[] | null;
    }
}
