/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const ThumbnailUrl: core.serialization.Schema<serializers.ThumbnailUrl.Raw, TwelvelabsApi.ThumbnailUrl> =
    core.serialization.string();

export declare namespace ThumbnailUrl {
    export type Raw = string;
}
