/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { TimeArrayItemFieldType } from "./TimeArrayItemFieldType";
import { TimeArrayItemFieldItems } from "./TimeArrayItemFieldItems";

export const TimeArrayItemField: core.serialization.ObjectSchema<
    serializers.TimeArrayItemField.Raw,
    TwelvelabsApi.TimeArrayItemField
> = core.serialization.object({
    name: core.serialization.string(),
    type: TimeArrayItemFieldType,
    description: core.serialization.string(),
    enum: core.serialization.list(core.serialization.string()).optional(),
    items: TimeArrayItemFieldItems.optional(),
});

export declare namespace TimeArrayItemField {
    export interface Raw {
        name: string;
        type: TimeArrayItemFieldType.Raw;
        description: string;
        enum?: string[] | null;
        items?: TimeArrayItemFieldItems.Raw | null;
    }
}
