/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const TotalInnerMatches: core.serialization.Schema<
    serializers.TotalInnerMatches.Raw,
    TwelvelabsApi.TotalInnerMatches
> = core.serialization.number();

export declare namespace TotalInnerMatches {
    export type Raw = number;
}
