/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const UpdatedAt: core.serialization.Schema<serializers.UpdatedAt.Raw, TwelvelabsApi.UpdatedAt> =
    core.serialization.date();

export declare namespace UpdatedAt {
    export type Raw = string;
}
