/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { VideoSearchSystemMetadata } from "./VideoSearchSystemMetadata";
import { UserMetadata } from "./UserMetadata";

export const VideoSearchItemMetadata: core.serialization.ObjectSchema<
    serializers.VideoSearchItemMetadata.Raw,
    TwelvelabsApi.VideoSearchItemMetadata
> = core.serialization.object({
    system: VideoSearchSystemMetadata.optional(),
    user: UserMetadata.optional(),
});

export declare namespace VideoSearchItemMetadata {
    export interface Raw {
        system?: VideoSearchSystemMetadata.Raw | null;
        user?: UserMetadata.Raw | null;
    }
}
