/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { VideoEmbeddingMetadata } from "./VideoEmbeddingMetadata";

export const VideoEmbeddingTaskVideoEmbedding: core.serialization.ObjectSchema<
    serializers.VideoEmbeddingTaskVideoEmbedding.Raw,
    TwelvelabsApi.VideoEmbeddingTaskVideoEmbedding
> = core.serialization.object({
    metadata: VideoEmbeddingMetadata.optional(),
});

export declare namespace VideoEmbeddingTaskVideoEmbedding {
    export interface Raw {
        metadata?: VideoEmbeddingMetadata.Raw | null;
    }
}
