/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const VideosListRequestWidth: core.serialization.ObjectSchema<
    serializers.VideosListRequestWidth.Raw,
    TwelvelabsApi.VideosListRequestWidth
> = core.serialization.object({
    gte: core.serialization.number().optional(),
    lte: core.serialization.number().optional(),
});

export declare namespace VideosListRequestWidth {
    export interface Raw {
        gte?: number | null;
        lte?: number | null;
    }
}
