/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { BaseEmbeddingMetadata } from "./BaseEmbeddingMetadata";

export const VideoEmbeddingMetadata: core.serialization.ObjectSchema<
    serializers.VideoEmbeddingMetadata.Raw,
    TwelvelabsApi.VideoEmbeddingMetadata
> = core.serialization
    .object({
        videoClipLength: core.serialization.property("video_clip_length", core.serialization.number().optional()),
        videoEmbeddingScope: core.serialization.property(
            "video_embedding_scope",
            core.serialization.list(core.serialization.string()).optional(),
        ),
        duration: core.serialization.number().optional(),
    })
    .extend(BaseEmbeddingMetadata);

export declare namespace VideoEmbeddingMetadata {
    export interface Raw extends BaseEmbeddingMetadata.Raw {
        video_clip_length?: number | null;
        video_embedding_scope?: string[] | null;
        duration?: number | null;
    }
}
