/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";
import { VideoSearchItemMetadata } from "./VideoSearchItemMetadata";
import { VideoMatch } from "./VideoMatch";

export const VideoSearchHit: core.serialization.ObjectSchema<
    serializers.VideoSearchHit.Raw,
    TwelvelabsApi.VideoSearchHit
> = core.serialization.object({
    rank: core.serialization.number(),
    itemId: core.serialization.property("item_id", core.serialization.string()),
    metadata: VideoSearchItemMetadata.optional(),
    matches: core.serialization.list(VideoMatch),
});

export declare namespace VideoSearchHit {
    export interface Raw {
        rank: number;
        item_id: string;
        metadata?: VideoSearchItemMetadata.Raw | null;
        matches: VideoMatch.Raw[];
    }
}
