/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as TwelvelabsApi from "../../api/index";
import * as core from "../../core";

export const VideoIndexingTaskSystemMetadata: core.serialization.ObjectSchema<
    serializers.VideoIndexingTaskSystemMetadata.Raw,
    TwelvelabsApi.VideoIndexingTaskSystemMetadata
> = core.serialization.object({
    duration: core.serialization.number().optional(),
    filename: core.serialization.string().optional(),
    height: core.serialization.number().optional(),
    width: core.serialization.number().optional(),
});

export declare namespace VideoIndexingTaskSystemMetadata {
    export interface Raw {
        duration?: number | null;
        filename?: string | null;
        height?: number | null;
        width?: number | null;
    }
}
