/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         assetId: "6298d673f1090f1100476d4c"
 *     }
 */
export interface IndexedAssetsCreateRequest {
    /** The unique identifier of the asset to index. */
    assetId: string;
    /** This parameter indicates if the platform stores the video for streaming. When set to `true`, the platform stores the video, and you can retrieve its URL by calling the [`GET`](/v1.3/api-reference/videos/retrieve) method of the `/indexes/{index-id}/indexed-assets/{indexed-asset-id}` endpoint. You can then use this URL to access the stream over the <a href="https://en.wikipedia.org/wiki/HTTP_Live_Streaming" target="_blank">HLS</a> protocol. */
    enableVideoStream?: boolean;
}
