/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as TwelvelabsApi from "../../../../api/index";
import * as core from "../../../../core";

export const AssetsListRequestAssetTypesItem: core.serialization.Schema<
    serializers.AssetsListRequestAssetTypesItem.Raw,
    TwelvelabsApi.AssetsListRequestAssetTypesItem
> = core.serialization.enum_(["image", "video", "audio"]);

export declare namespace AssetsListRequestAssetTypesItem {
    export type Raw = "image" | "video" | "audio";
}
