/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../index";
import * as TwelvelabsApi from "../../../../../../../../api/index";
import * as core from "../../../../../../../../core";

export const CreateAsyncEmbeddingRequestInputType: core.serialization.Schema<
    serializers.embed.v2.CreateAsyncEmbeddingRequestInputType.Raw,
    TwelvelabsApi.embed.v2.CreateAsyncEmbeddingRequestInputType
> = core.serialization.enum_(["audio", "video"]);

export declare namespace CreateAsyncEmbeddingRequestInputType {
    export type Raw = "audio" | "video";
}
