/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../index";

export interface KnowledgeStoresListResponse {
    /** An array containing the knowledge stores. */
    data?: TwelvelabsApi.KnowledgeStore[];
    pageInfo?: TwelvelabsApi.PageInfo;
}
