/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as TwelvelabsApi from "../../../../api/index";
import * as core from "../../../../core";
import { SearchRetrieveResponsePageInfo } from "./SearchRetrieveResponsePageInfo";
import { SearchItem } from "../../../types/SearchItem";
import { SearchPool } from "../../../types/SearchPool";

export const SearchRetrieveResponse: core.serialization.ObjectSchema<
    serializers.SearchRetrieveResponse.Raw,
    TwelvelabsApi.SearchRetrieveResponse
> = core.serialization.object({
    pageInfo: core.serialization.property("page_info", SearchRetrieveResponsePageInfo.optional()),
    data: core.serialization.list(SearchItem).optional(),
    searchPool: core.serialization.property("search_pool", SearchPool.optional()),
});

export declare namespace SearchRetrieveResponse {
    export interface Raw {
        page_info?: SearchRetrieveResponsePageInfo.Raw | null;
        data?: SearchItem.Raw[] | null;
        search_pool?: SearchPool.Raw | null;
    }
}
