/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TasksCreateResponse {
    /**
     * The unique identifier of the video embedding task. You can use the identifier to:
     * - Retrieve the status of your task by invoking the [`GET`](/v1.3/api-reference/video-embeddings/retrieve-video-embedding-task-status) method of the `/embed/tasks/{task_id}/status` endpoint.
     * - Retrieve the embedding by invoking the  [`GET`](/v1.3/api-reference/video-embeddings/retrieve-video-embeddings) method of the `/embed/tasks/{task_id}` endpoint.
     */
    id?: string;
}
