/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../../../index";

export interface TasksRetrieveResponseVideoEmbedding {
    metadata?: TwelvelabsApi.VideoEmbeddingMetadata;
    /** An array of objects containing the embeddings for each video segment and the associated information. */
    segments?: TwelvelabsApi.VideoSegment[];
}
