/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../../../index";

/**
 * An object that provides information about pagination.
 */
export interface TasksListResponsePageInfo {
    limitPerPage?: TwelvelabsApi.LimitPerPageSimple;
    page?: TwelvelabsApi.Page;
    totalPage?: TwelvelabsApi.TotalPage;
    totalResults?: TwelvelabsApi.TotalResults;
}
