/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../../../../index";

/**
 * @example
 *     {
 *         entities: [{
 *                 name: "My entity",
 *                 assetIds: ["6298d673f1090f1100476d4c", "6298d673f1090f1100476d4d"]
 *             }]
 *     }
 */
export interface EntitiesCreateBulkRequest {
    entities: TwelvelabsApi.entityCollections.EntitiesCreateBulkRequestEntitiesItem[];
}
