/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface EntitiesUpdateRequest {
    /** The new name for the entity. */
    name?: string;
    /** An updated description for the entity. */
    description?: string;
    /** Updated metadata for the entity. If provided, this completely replaces the existing metadata. Use this to store custom key-value pairs related to the entity. */
    metadata?: Record<string, unknown>;
}
