/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as TwelvelabsApi from "../../../../index";

/**
 * @example
 *     {
 *         page: 1,
 *         pageLimit: 10,
 *         name: "foo",
 *         status: "processing",
 *         sortBy: "created_at",
 *         sortOption: "desc"
 *     }
 */
export interface ListAllEntitiesRequest {
    /**
     * A number that identifies the page to retrieve.
     *
     * **Default**: `1`.
     */
    page?: number;
    /**
     * The number of items to return on each page.
     *
     * **Default**: `10`.
     * **Max**: `50`.
     */
    pageLimit?: number;
    /**
     * Filter entities by name.
     */
    name?: string;
    /**
     * Filter entities by status.
     */
    status?: TwelvelabsApi.ListAllEntitiesRequestStatus;
    /**
     * Field to sort by.
     */
    sortBy?: TwelvelabsApi.ListAllEntitiesRequestSortBy;
    /**
     * The sorting direction. The following options are available:
     * - `asc`
     * - `desc`
     *
     * **Default**: `desc`.
     */
    sortOption?: string;
}
